sunset-wasteland/sunset-wasteland

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/mob/living/carbon/human/species.dm

-Fixes horrifying log spam about eye types in char creation
-Fixes the bank vault stairs being broken at the bottom
-Fixes the bank backdoor shutter not working properly
-Fixes bottle selection at bank and mayors office having the wrong file paths
-Fixed broken metal armor sprite

Round 1 Issues

---

code/modules/jobs/job_types/bos.dm
code/modules/jobs/job_types/enclave.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/silicon.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/vault.dm
code/modules/jobs/job_types/wasteland.dm

New Timers

---

code/__DEFINES/dcs/signals.dm
code/_onclick/drag_drop.dm
code/datums/components/combat_mode.dm
code/datums/components/lockon_aiming.dm
code/modules/client/client_defines.dm
fortune13.dme

Makes client face mouse during combat mode.
Combat quality of life improvement.
:cl:
tweak: Client now faces mouse during combat mode.
/:cl:

Combat mode facing

---

code/modules/reagents/chemistry/recipes/medicine.dm

Fuck fermichem, all my homies hate fermichem. Synthtissue will now mix without the need for fermichem mechanics.
Jokes aside, you need it for organ repair surgery, and it's a QoL change for FoA
:cl:
balance: Synthtissue can be made without fermichem
/:cl:

disables fermichem for synthtissue

---

code/datums/components/crafting/recipes/recipes_bottling.dm
code/datums/components/crafting/recipes/recipes_medicine.dm
code/modules/WVM/wmv_buyer.dm
code/modules/food_and_drinks/drinks/drinks/bottle.dm

Primary changes are to the Wasteland Trader machine. Some prices have been tweaked, materials are now tradable as sheets instead of ore, and a bunch of medicinal items and all export alcohol bottles have been added to the list.
You can now physically craft sealed bottles under the bottling tab if you have a bottling press and 50u of the alcohol you want to export. Become a wasteland brewer today!
Adds a more involved crafting recipe for the primitive defib
Honest caps for honest work, and more caps to go around encourages more trading, more robbing, and more ransoming.
:cl:
add: Added crafting recipes under bottling for exportable alcohol.
code: Wasteland Trader vendor accepts sheets instead of ore now.
refactor: Overhauled the list of goods you can sell to the Wasteland Trader vendor …

Economy update+craftable primitive defib

---

code/modules/jobs/job_types/wasteland.dm

Minor Job Desc Edit

---

code/datums/components/crafting/recipes/recipes_bottling.dm

Added names to the new bottling recipes, should fix them not showing up.
:cl:
fix: Added names to the new bottling recipes, should fix them not showing up.
/:cl:

Should fix the new bottling recipes not showing up

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Adds K-Rations (two breakfast, two dinner, three lunch) to the Ranger station.
They're Ranger rations, it makes sense for them to be there instead of just two pieces of junk food.
:cl:
add: added k-rations to the Ranger station
/:cl:

Feeds the Rangers

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

The BoS and NCR lack ID/radio terminals, used to alter ID cards and cut off/relink radios, as well as any spare dog tags. This means that if you lose your radio/ID, you cannot replace it by _any means_.
This PR adds ID/radio terminals to the Captain's office, ID terminals to each Head office, and a radio terminal to the BoS armoury. Those offices also now have spare tags, just like the Legion.
If you don't have your ID or radio, you're pretty heavily hampered in what you can _do_. There should be _some_ way to replace them.
:cl:
add: spare tags, ID consoles and radio terminals to NCR/BoS
/:cl:

Gives the NCR/BoS/legion radio/ID terminals and spare ID cards

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

The NCR/Legion mini-dungeons (used to get advanced workbenches and ammo books) weren't brought to the current Dungeons.dmm file, preventing them from being accessible (and the NCR's ladder to their dungeon was missing entirely). This fixes that.
The factions are balanced with the assumption they'll have the loot from these mini-dungeons at roundstart.
:cl:
fix: fixed NCR/Legion mini-dungeons being inaccessible
/:cl:

fixes NCR/Legion dungeons

---

code/modules/research/designs/comp_board_designs/comp_board_designs_sci.dm
code/modules/research/designs/machine_designs.dm
code/modules/research/designs/machine_desings/machine_designs_sci.dm
code/modules/research/techweb/_techweb_node.dm

Removes certain exploitable circuit boards from being printable with the circuit imprinter.
Old exploit allows said circuits to be used to boost research by insane amounts. While the circuits are no longer printable, replacement parts can still be found and looted in the world.
:cl:
balance: removed Research server and control console circuits from being printable
/:cl:

removed some research circuits

---

code/modules/jobs/job_types/followers.dm

Alters Followers spawning text to say that you are **not** obligated to help everyone. A lot of people, both in and out of the faction (speaking in general of F13) think Followers have to revive anyone thrown onto their desk. 
Having one faction be obligated to help absolutely everyone, even people who are actively opposed to them, is... weird.
:cl:
tweak: tweaked Followers spawning text
/:cl:

Alters Followers flavour text

---

code/modules/research/designs/ammolathe_designs.dm

:cl:
del: Removed excess 9mm crafting option that only produced a single bullet.
fix: Fixed .22LR rubber ammo box creating regular ammo instead of rubber ammo.
tweak: re-labeled 10mm extended pistol magazine to 10mm SMG magazine for easier understanding it won't fit in a 10mm pistol
/:cl:

minor ammolathe fixer

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/shuttles/southbunker_elevator.dmm
code/datums/shuttles.dm
code/game/area/Space_Station_13_areas.dm
code/game/objects/items/circuitboards/computer_circuitboards.dm
code/modules/shuttle/f13.dm

Added a new bunker dungeon to the map alongside minor quality of life tweaks.
Quality of life improvements, replaced generic loot closets with locked and anchored variants to counter players attempting to cheese the mob reaction time. And who doesn't want a new raid to experience?
:cl:
add: added throwing spear quiver to legion camp armory
add: added new bunker
tweak: minor map tweaks all around
balance: replaced generic loot closets inside dungeons and mini-dungeons
:cl:

Added new structure

---

code/modules/WVM/wmv_buyer.dm

Nerfs mining income down to 10% of original value.
Headmin consensus decreed that mining was just too OP of an income source, after several days of testing.
:cl:
balance: Selling minerals at Bighorn is now only 10% as profitable as before, due to flooding of the market.
/:cl:

Reigns in mining economy to be more in line with other sources of trade income

---

code/datums/components/crafting/recipes/recipes_primal.dm
code/modules/jobs/job_types/wasteland.dm

Maybe in the future, I'll make it craftable again. But you'll have to kill a brand new megafauna to get it. Host said to nix it for now though because it's actually OP and too easy to get with spear cheese.
Like seriously, this thing is crazy good for an early game weapon. Should be made a megafauna thing instead.
:cl:
balance: makes deathclaw spears uncraftable until a megafauna can be added to justify how insane this spear is.
/:cl:

Makes deathclaw spear uncraftable.

---

code/modules/mob/dead/new_player/sprite_accessories/hair_face.dm
code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm

Closes #60 
Fixes the following hairstyles (and one facial hair):
Amazon
Beachwave
Bedhead
Big Mohawk
Bun Low
Emo Half Shave
Emo Long Side
European Cut
Gentle (Alt)
Jessica
Legion Shave
Pigtails 4
Ponytail 8
Sabitsuki
Side Cut
Tribal Braid
Very Long Beard
We had the icon files, but we just needed to point the style entries to where the icons actually were.
Less funny ERROR people.
:cl:
fix: All hairstyles and facial hairstyles in the character creation menu should now work as intended.
/:cl:

Fixes several hairstyles

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Missed one or two minor details.

Quick Mass Fusion Edits

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Adds a deconstructive analyzer board to the followers base, and an ammo bench to the BoS bunker.

Let their be AMMO AND RESEARCH!

---

fortune13.dme

Resolves the issue with auto-merge

Git compile fix

---

code/modules/projectiles/projectile/bullets/pistol.dm

All incendiary ammo is now unable to stack fire. If you have fire stacks already, then being hit with incendiary ammo can only raise your fire stacks up to the amount it would usually apply. In other words: if you have 0.5 stacks, and get hit with incendiary 10mm (which applies 1 stack), you will only recieve half a stack.
This keeps the gimmick of incendiary ammo while also fixing the exponential fire damage it can deal when uncapped.
:cl:
balance: incendiary ammo no longer stacks fire
/:cl:

Nerfs incendiary ammo

---

modular_citadel/code/modules/client/loadout/suit.dm

Readds Samurai armor in the loadout.  4pt cost to make players pay for their weebery.  It's only moderately better in melee than a bomber jacket, so its kind of rubbish.  But hey, at least its nice and rust colored.

Readds Samurai armor to match the kabuto in loadout.

---

code/modules/jobs/job_types/legion.dm

Reverts titles changes made in #95 to the Legion Explorer jobs.

Restores Legion Venator Title

---

fortune13.dme
modular_sunset/code/modules/clothing/masks/gasmask.dm
modular_sunset/code/modules/fallout/obj/trash_stack.dm

This reverts/removes modular trash stack addition added in #103 due it not working at all (it probably needed to be in the separate `GLOBAL_LIST_INIT` stuff, but since it's just two items I will not bother with it atm).
As a consolation bonus, rewords descriptions for full gas masks.
Yes, I only discovered it today after personally checking more than 10 garbage piles on localhost.
Alas, useless code. Might rework it properly later if code gets more modular (or otherwise) items.
:cl: Anonymous
spellcheck: Rewords description of the full gas mask.
/:cl:

Removes modular trash_stack.dm due it not working

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Fixed excess fencing blocking fence gates at the Bighorn market and fixed access for the underground workshop.

Bighorn E&E - workshop and market fence gates hotfix

---

code/modules/fallout/obj/snacks.dm

Making the brahmin liver into liver, instead of liver-tongues...?

Brahmin Liver desc fix

---

code/modules/mob/living/simple_animal/hostile/f13/raider.dm

Expands Raiders from just screaming Hurry, hurry, hurry to a handful of iconic sayings, and at least one meme.  Feel free to cut the meme, or ask me to.  lol

Raider Smacktalk - I'm gonna touch you in the intestines Edition

---

code/datums/datacore.dm
code/modules/jobs/job_types/khan.dm

Basically your ID, if it doesn't have a pre-existing assignment on it like many do, should now display your rank based on your job title.
Khans can now tell what rank they and other Khans are from seeing their tattoos.
:cl:
fix: Khan IDs now properly display jobs
refactor: Assigned role in the mind datum is now based on the living person's job variable BEFORE being marked as Unassigned per the default, allowing for some potential new utility in the future, such as functioning wages.
/:cl:

Fix for Khan ranks showing as 'NOPE'

---

code/modules/mob/living/carbon/human/species_types/dwarves.dm

Allows Anthro Dwarves to exist.
Known issue
- Must turn on mismatched markings to get a snout

Krotos Squatdog Code

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

minor adjustments, added QoL smart fridges to some kitchens, adjusted curtains, replaced fluff railing, fixed areas, gave followers self defense equipment

Bighorn E&E Hotfix2

---

code/modules/fallout/reagents/medicines.dm

Overhauls most FO13 medicine types to heal slower.
Slows down the pace making it so players strategize more instead of just bum rushing into combat and popping stims like 
they were snacking on chips.
Note; I've spent a few hours balancing the numbers but **require more field testing** through others' localhosting; doing various things such as dungeon clears so this rebalance won't be merged immediately.
:cl:
Super Stimpak
~~100  HEAL, 0:58~~
Stimpak
~~100  HEAL, 1:46~~
Imitation Stimpak
~~42.5  HEAL, 1:25~~
Bitters
~~100  HEAL, 1:00~~
Healing Poultice
~~100  HEAL, 1:39~~
Healing Powder
~~65  HEAL,  2:00~~
update: all values above increased by 25%-40%
med-x slightly nerfed
:cl:

Medicine rebalance, survival mode edition.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Removed wrecks that can't be salvaged.

NCR Base Hotfix1

---

code/game/objects/structures/lamp_post.dm

Makes lamp posts destructible, also made them a bit brighter.

lamp post fix

---

modular_sunset/README.md

Was supposed to be included with another PR ages ago but said PR was reverted temporarily and the readme was left over.
**Make sure to give it a read if you're contributing with new assets or features.**

README for modular_sunset

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

access fix for workshop and storage room

Bighorn E&E hotfix3

---

code/controllers/configuration/entries/general.dm

Reverts sunset-wasteland/sunset-wasteland#102

Revert "Adjusted round timers."

---

code/controllers/configuration/entries/general.dm

Reverts sunset-wasteland/sunset-wasteland#139
Bit of a dispute in regards to how long rounds should last.

Revert "Revert "Adjusted round timers."" REVERTED EDITION

---

code/modules/WVM/wvm.dm

Why?  Because the thing was basically a 1911 Vendor and needed some more stock!
Adds to the Weapon Vendor
- .22 Pistol - 110 Caps
- 9mm Pistol - 150 Caps
- 10mm Pistol - 150 Caps
- Colt Revolver - 160 Caps
- Cowboy Repeater - 160 Caps
- M1 Carbine - 170 Caps
Are the prices good?  Idk, they're probably too high on some stuff, but lets just call that wasteland huckstery from a Protectron that wants to rip you off.  Ain't capitalism grand?  :eagle: 
Tested and working.

Adds more guns to the gun vendor

---

code/modules/jobs/job_types/bos.dm

Every combat role (more or less) has a sharp melee weapon that can fit in a boot or backpack. It's a standard. Sharp weapons are useful.
Sharp weapons are useful and as a backup melee weapon need to exist. Even when paladins and SPs pick their melee loadouts they don't get a sharp melee option. It's useful for stuff like making bandages from gauze or well, using it to poke at stuff. Near all BOS roles have a hunting knife, frankly it's just an oversight.
:cl:
add: Gave Paladin and Senior Paladin a hunting knife.
/:cl:

Gives Paladin and Senior Paladin a knife

---

modular_sunset/code/modules/clothing/head/f13head.dm
modular_sunset/code/modules/clothing/suits/f13suits.dm

This allows color-marked coats and helmets to be reinforced with armor plates.
**Known Issue:** Armor plates will be placed into the pocket when you try to reinforce olive trenchcoats. You have to take them out every time you apply them.
Was suggested in the Discord; Moves outfit from being underrated.
:cl: Anonymous
tweak: You can now reinforce color-marked olive trenchcoats and helmets.
/:cl:

Allows crude militaristic outfits (AKA GWTB-inspired) coats and helmets to be reinforced

---

code/controllers/configuration/entries/game_options.dm
code/controllers/subsystem/mapping.dm

Fixes multiple runtimes and disables unused feature.

VR runtime fix

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Tweaks some railings/balconies in bighorn to be usable and not block vision.
Adds usable area to this space (currently you cannot walk on the balcony))
Fixes a visual bug with the right room.
:cl:
tweak: tweaked some balconies in bighorn
/:cl:

Fixes some balconies in bighorn

---

modular_citadel/code/modules/client/loadout/__donator.dm
modular_citadel/code/modules/client/loadout/donor.dm

DM code being fussy with ckeys that have special characters in them.

fluff item fix2

---

code/modules/jobs/job_types/khan.dm

Fixes missing access for Noyan and Steward roles.

Khan leader access fix

---

modular_sunset/code/modules/client/loadout/head.dm
modular_sunset/code/modules/client/loadout/mask.dm
modular_sunset/code/modules/client/loadout/suit.dm

This PR lowers loadout cost of *every* Blastwaver clothing down to 2. Might gone overboard here, though, especially with aesthetic gasmask.
It was requested, plus it is low-tier armor anyway. Also saves some points for the gloves and boots for complete, proper set.
:cl: Anonymous
tweak: Decreases loadout cost of color-marked coats, helmets, peaked caps and an aesthetic gasmask down to 2.
/:cl:

Lowers the loadout cost for GWTB/RGBY outfits

---

.vscode/launch.json
.vscode/tasks.json

Updates the VSC build tasks so that building (Ctrl+Shift+B) and running w/debugging (F5) works as intended.
Better coding workflow.
:cl:
code: Updated the VSC build tasks.
/:cl:

Updates VSC build tasks

---

code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

Nerfs player (FEV created) ghouls. 
Health to 200 from 320
Regen to 20/ lifetick from 32/ lifetick
Player FEV Mutation Ghouls are uh.... special. By special I mean **Regenerate more than most bullets can deal damage**
This change makes player ghouls more fragile, or at least possible to kill without dedicating a player train to murder them.
:cl:
balance: FEV Ghoul to 200 Health
balance: FEV Ghoul regen to 20
/:cl:

Nerfs to FEV Ghouls

---

code/modules/fallout/misc/gang_items.dm
code/modules/fallout/misc/gangs.dm

-Balances the price of items to match wasteland a bit better, and prices will allow outlaws who've joined late to reasonably afford items.
-Adds a new & expensive bundle called 'Big Boss' costing 1200 caps containing: a Salvaged Raider PA kit, Winchester shotgun(with generic ammo), and two drugs because of filler.
Adds a small piece of content to an outdated piece of the game, as well as includes actually decent prices in the outlaw gang tool.
:cl:
add: New Bundle
tweak: Changed some prices to be reasonable.
/:cl:

Updates Gangtool [FIXED]

---

code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

Adjusts decomposition rates of simple mob corpses.
Allows animal bodies to linger for longer so certain tribal crafting materials don't go to waste.
:cl:
tweak: Decomposition rate adjusted.
:cl:

Adjusted simple mob decomposing.

---

code/datums/weather/weather_types/acid_rain.dm

Removed the acid reagent effect as it always ended up melting equipment way too quickly, instead replaced with flat burn damage.
Characters no longer loosing their power armor and rest of gear from a quick dash through bad weather.
:cl:
balance: changed acid rain weather effect from acid reagent to burn damage
:cl:

Removed acid reagent from acid rain.

---

code/modules/fallout/misc/gang_items.dm

On my personal files, I had fixed this error, and after downloading the codebase I realized I placed an older file with this typo. This is my first PR in a long time so I do apologize.
A small typo from my ironically fixed update.
:cl:
/:cl:

Small typo [Not urgent]

---

code/game/objects/structures/crates_lockers/closets.dm

Increases the amount of items that can be stored inside a 'closet' type storage. Mob capacity remains the same.
More realistic storage capacity as closets are usually as tall as a locker but wider.
:cl:
tweak: closets can now hold 16 items instead of 8
tweak: anchored closets can now hold 32 items instead of 30
:cl:

Adjusted closet storage space.

---

code/modules/client/preferences.dm

The Not My Fault Update

---

code/game/objects/items/stacks/medical.dm

All of these items have a substantial apply delay and are not usable in combat. They also require targeting injured limbs instead of simply being a chem heal (such as stimpacks, powders, etc)
The reduction in the previous PR would make these effectively unusable. This reverts those changes to sutures to the old values
Out of combat healing isn't what needs a nerf?
:cl:
fix: reverted suture healing values for out of combat healing.
/:cl:

Reverts nerfs to suture items

---

code/game/objects/items/devices/radio/headset.dm

Adds a town encryption key to khan headsets
If the Khan are town guards, they should have the town channel.
:cl:
tweak: adds town encryption key to khan headsets.
/:cl:

Adds town encryption keys to khan headsets

---

code/datums/components/crafting/recipes/recipes_assemblies.dm
code/datums/components/crafting/recipes/recipes_explosives.dm
code/datums/components/crafting/recipes/recipes_medicine.dm
code/datums/components/crafting/recipes/recipes_misc.dm
code/datums/components/crafting/recipes/recipes_primal.dm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/datums/components/crafting/recipes/recipes_tools.dm
code/game/machinery/deployable.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/turfs/f13concrete.dm
code/modules/hydroponics/grown/towercap.dm

First pass of the crafting times, increases most 'complex' furniture things by %50-%75 and increased medicine/drug crafting by %25.

Crafting time rebalance

---

code/game/objects/items/melee/f13onehanded.dm
code/modules/mob/living/simple_animal/animal_defense.dm

Fixes the Yao Guai gauntlet to actually do any damage at all. Also makes it so simplemobs take damage equal to your unarmed damage then you punch them instead of some random arbitrary number, making unarmed weapons work on them without having to hold them in your hands.
:cl:
fix: yao guai gauntlet deals damage now
fix: simplemobs no longer ignore unarmed weapons
/:cl:

Less unarmed jank (Fixes Yao Guai Gauntlet, Unarmed weapons affect simplemobs)

---

code/modules/arousal/genitals_sprite_accessories.dm

Un-comments the fun furry bits.
Simply removes a few bulk comments that re-enables furry genitals like knots, hemi's, etcetera, along with their tauric counterparts.
Allows for players to have variety in character customization.
:cl:
add: Re-enables furry genitals as a selectable option.
/:cl:

Re-enables the furry "junk".

---

code/__DEFINES/is_helpers.dm
code/modules/mob/living/carbon/human/species_types/ghoul.dm
config/game_options.txt

Adds a new type of ghoul in the form of Ghoulified Anthromorphs. 
These new ghouls allow you to choose whatever appearance that you might want, including the variety of insects, aquatic, avian, mammalian, and lizardfolk.
More customization for races is a good thing because it will allow players to utilize ghoulish perks as non-human sprites, i.e. if a player wanted a ghoulified canine or similar, that is now possible.
:cl:
add: Added the Ghoulified Anthromorph race
tweak: Tweaked the helper for IsGhoul to now include GhoulAnthro as well.
server: Game_Options.txt (//config/game_options.txt) may need to have the line 'ROUNDSTART_RACES ghoulanthro' added underneath the roundstart races in order for this to work.
/:cl:

Adds Ghoulified Anthromorphs

---

code/modules/projectiles/boxes_magazines/internal/_cylinder.dm

Makes it so revolvers no longer fill up whatever storage they're in with spent casings when reloading them. Now they drop them on the floor like every single other gun with an internal mag does.
:cl:
fix: revolvers inside your tight backpack no longer blast their load into it when you cram bullets into them
/:cl:

Fixes revolvers emptying themselves into you after reloading

---

code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/devices/PDA/PDA_types.dm

I mostly just changed some of the flavor text on the starting notes in PDAs to be more in line with Fallout lore.
The old PDA text referred to a company in SS13 lore, a space station and called it a Personal Data Assistant, which lore wise. Pip-Boys ain't.
I also think the Pip-Boy giving you useless directions is funnier.
:cl:
tweak: tweaked the starting notes on PDAs.
/:cl:

Minor lore fixes to Pip-Boys.

---

code/modules/mob/living/carbon/human/species_types/ipc.dm
code/modules/mob/living/carbon/human/species_types/synthanthro.dm
code/modules/mob/living/carbon/human/species_types/synthliz.dm
code/modules/mob/living/carbon/update_icons.dm
code/modules/surgery/bodyparts/_bodyparts.dm

Finally enables Synthetic Anthromorphs, Synthetic Lizardfolk, and IPCs having actual, honest to god robotic limbs.
Closes #233 where Synthetic Species acted as organic species in game. 
:cl:
fix: Fixes #233 and makes synthetic species actually synthetic.
/:cl:

Enables Robotic Limbs for Synthetic Species

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
code/modules/power/cell.dm

Fixes #110 by deleting the two Microfusion Breeders from Mass Fusion Power plant. They shouldn't have been mapped in anyways. It also fixes the issues of Microfusion Breeders not being self charging as advertised.
Removes a useless item from the game that you shouldn't be able to get anyways.
:cl:
tweak: Enables self charging on Microfusion Breeders due to being the ammo for Recharger Pistols/Rifles.
del: Removed two instances of Microfusion Breeders from Mass Fusion because they shouldn't exist due to being the Recharger Pistol/Rifle's ammo source. Fixes #110 
/:cl:

Removes Microfusion Breeders from map.

---

code/controllers/configuration/entries/general.dm
code/modules/client/border_control.dm
code/modules/client/client_procs.dm
code/modules/mob/dead/new_player/new_player.dm
config/config.txt

I feel like the interview system is kinda built for this, but it didn't work for me when I tried it and I didn't look too deeply into it. That might be better.
:cl:
/:cl:

Adds a mode to border control that allows them to still join the lobby.

---

code/datums/components/crafting/recipes/recipes_misc.dm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/game/objects/items/melee/f13twohanded.dm
code/game/objects/items/storage/fancy.dm
code/modules/fallout/obj/structures/obstacle.dm
code/modules/fallout/reagents/alcohol.dm
code/modules/fallout/turf/walls.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/reagents/chemistry/recipes/medicine.dm

Fixes:
- Puts all Miscellaneous recipes into the same category
- Moves the flower crown recipes to Misc Clothing
- War Maces are now able to be wielded
- Inviting tribals to your tribe now works
- The Spiritual trait from Datura Tea now gets removed after the reagent is gone
QoL:
- Adds craftable rolling paper to the Miscellaneous section (1 natural paper, or 10 natural paper + 1 cardboard in bulk)
- Completely redoes the Barricade -> Wall building code and turns it into a radial menu. You can build Wooden, House and Interior walls with Wood, House and Wood Framed Windows with Glass, and Tent Walls and Tent Flaps with Cloth.
Bugs bad. Quality of life good.

Fixes and QoL

---

_maps/_basemap.dm

Adds all the map files from pahrump.json to _basemap, which means they'll be compiled in for unit testing, giving errors if the maps are broken.
This should catch issues with nonexistent or nonsensical variables.

Add Yuma maps to CI compile maps step

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Not done yet, just to get my latest work on the repo

a bit of map work

---

code/modules/integrated_electronics/core/special_pins/string_pin.dm

Caps the length of data in string pins to the size of a message, which is currently 4096 characters.
Sending potentially unlimited amounts of data is a DoS vector, and even if it's done unintentionally it can still cause issues.

Cap string pin data to message-sized

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Reverts sunset-wasteland/sunset-wasteland#261
reverting to roll in map fixes

Revert "a bit of map work"

---

code/modules/jobs/job_types/bos.dm

- - -
Simple edit to bring BoS roles in line with the codex, as it is currently written.
This only touches the titles of the roles themselves, not anything else.
- - -

Lore Coherency

---

code/modules/admin/admin.dm

Should allow all ranks with Admin perms to access job management.

job management admin perm fix

---

code/modules/jobs/job_types/bos.dm

- - -
Provides Knights with the ability to wear PA, in line with the codex.
- - -

BoS Pass #1

---

code/__DEFINES/dcs/signals/signals_mob_main.dm
code/datums/brain_damage/brain_trauma.dm
code/datums/components/killerqueen.dm
code/datums/components/twohanded.dm
code/datums/datum.dm
code/datums/mind.dm
code/game/mecha/mecha.dm
code/game/objects/structures/execution.dm
code/game/objects/structures/kitchen_spike.dm
code/modules/mapping/space_management/space_reservation.dm
code/modules/mob/dead/dead.dm
code/modules/mob/dead/new_player/login.dm
code/modules/mob/dead/observer/login.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/carbon/human/login.dm
code/modules/mob/living/login.dm
code/modules/mob/login.dm
code/modules/modular_computers/computers/item/computer.dm
code/modules/spells/spell_types/shapeshift.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/surgery.dm
fortune13.dme

Pulls some commits from Coyote Bayou to fix runtimes and improve stuff.
Fixes runtimes when ghosts move.

Partial sync from downstream

---

code/__HELPERS/type2type.dm
code/_onclick/hud/hud.dm
code/_onclick/hud/screen_objects/sprint.dm
code/_onclick/hud/screen_objects/stamina.dm
code/datums/components/combat_mode.dm

Fixes #160 by adding extra code to handle switching things to the Citadel UI icon file if necessary when you switch UI styles. Otherwise, it would get stuck as one style or disappear entirely.
All UI elements should now switch between styles properly. (The intents icon is not skinned and was instead edited directly, which is bad. TODO: fix that.)
Bugfix! And not everyone likes the Fallout UIs.
:cl:
fix: fixed certain UI elements disappearing when changing styles mid-round
tweak: made UI style changing work more reliably
/:cl:

Fix #160, extra support for non-Fallout UIs

---

code/modules/fallout/machinery/alchemy_table.dm
code/modules/reagents/chemistry/machinery/chem_master.dm
fortune13.dme
tgui/packages/tgui/interfaces/AlchemyTable.js
tgui/packages/tgui/interfaces/ChemMaster.js

Rewrites the alchemy table to have its own separate UI (`AlchemyTable.js`), although it shares some components with `ChemMaster.js`. No unmodified code should be duplicated, but I might have missed something.
Removes the `primitive` var from the chemmaster since it's a bad design practice. (Then again, most of chemmaster code is pretty old and bad...)
The old alchemy table code was broken (had a typo or two preventing the amounts from working) and used some really awful control code. This version has its own UI file and its behavior is defined separately.
:cl:
fix: fixed alchemy table amount selectors not visually working
refactor: refactored the alchemy table, please report anything that breaks
/:cl:

Refactor alchemy table

---

code/modules/mining/mint.dm

Fixes the mint machine UI, using a cherry-picked commit from Citadel.
Fewer issues = good.

Port mint machine UI fix from Citadel

---

code/modules/fallout/misc/gang_items.dm

Fixes #184. The path pointed to a grenade recipe rather than the grenade itself.
Fixes #184.

Fix gangtool spawning a grenade recipe instead of a grenade

---

code/datums/components/crafting/crafting.dm
code/datums/components/crafting/recipes.dm
code/datums/components/crafting/recipes/recipes_explosives.dm

Adds a system for making recipes granted by traits.
The basic usage is just `granting_trait = TRAIT_WHATEVER`, but you can use more complex combinations. For example, to require two traits, you could use `granting_trait = list(TRAIT_FIRST, TRAIT_SECOND)`. To require one of two traits, you can use `granting_trait = list(list(TRAIT_EITHER, TRAIT_OR))`. You can even combine these, for things like `list(list(TRAIT_FIRST, TRAIT_SECOND), list(TRAIT_EITHER, TRAIT_OR))`, which would be "TRAIT_FIRST or TRAIT_SECOND, and TRAIT_EITHER or TRAIT_OR."
Currently, the only traits this is used by are both locked, but this is an extensible system.
These traits never worked; now they do.

Allow crafting recipes to be granted by traits

---

_maps/map_files/Pahrump-Sunset/Warren.dmm

Warren somehow got a bunch of invalid space turfs. I removed them all.
Space is bad. It's opaque and dense which means it looks like a worse bug than it is.

Fix space turfs on the Warren map

---

code/datums/weather/weather.dm
code/game/area/areas.dm
code/modules/mapping/map_template.dm

Potential fix, sort of, for #291. Will fix weather not starting, but will also lead to an issue where areas not getting weather will get the weather overlay. Without totally redoing how weather overlays are done, there's not a way to avoid that other than using distinct areas for each z-level.
It fixes a runtime that stopped rain/ash storms from working most of the time.

Implement experimental multiz area compatibility

---

code/modules/clothing/under/f13.dm
modular_citadel/code/modules/client/loadout/uniform.dm

- Adds the raider rags and raider leathers to the loadout.
- Replaces a 'unanimously' that shouldn't be in the raider rags description.
Request on the Discord, quality of life loadout improvement.
:cl:
add: Added raider rags and raider leathers to loadout
/:cl:

Add raider rags and raider leathers to loadout

---

code/modules/atmospherics/environmental/LINDA_system.dm

Makes two changes to atmos code for (potentially) better performance, which is mainly important to reduce the 50 second startup time contribution it has.
- Hardcodes the space-adjacency argument to the auxtools turf adjacency update proc, since we don't use space at all and space was soft-removed, since it's dense now. This contributed a time save of between 10-15% in testing.
- Removes an unnecessary istype in some atmos init code that checks turf contents. This produced about a 15-20% time save in testing.
Overall, in my testing it was about a 1/3 decrease in startup time. What's not to love?

Tweak atmos for performance

---

code/modules/clothing/suits/f13factionarmor.dm

fixed directory of some of the centurion armors,
nerfed the paladin slayer's melee and bullet protection and buffed its plasma and bomb resistance

critical cent armor fix + balance touch up

---

code/game/machinery/water_purifier.dm
code/game/objects/items/melee/misc.dm
code/game/objects/items/storage/belt.dm
code/game/objects/structures/tribal_torch.dm
code/modules/fallout/misc/gangs.dm
code/modules/fallout/misc/tribes.dm
code/modules/integrated_electronics/subtypes/atmospherics.dm
code/modules/mob/living/carbon/human/species_types/golems.dm
code/modules/mob/living/simple_animal/bot/secbot.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile/bullets/dart_syringe.dm

Fixes several runtimes:
- Fix invalid or ugly to_chat messages.
- Fix to_chat null message runtime from gangs.
- Fix water purifier runtime from null output var.
- Fix runtime in simple_animal.dm:358 from null loot.
- Prevent hitting things with both a gun and a bayonet at once.
Fixes a bunch of runtimes!

Runtime fixes, August 11 2022

---

code/datums/components/fantasy/_fantasy.dm
code/datums/components/fantasy/prefixes.dm
code/datums/components/fantasy/suffixes.dm
code/game/objects/items/grenades/flashbang.dm
code/modules/clothing/clothing.dm
code/modules/mob/mob.dm

- Fixes null/empty to_chat calls from visible_message
- Ports updates to visible_message from TG and Citadel
- Fixes unnecessary duplicate signal registration from damaged clothes
- Refactors fantasy affixes to be less shit and avoid tactical prefix runtimes
- Fixes the incorrectly ordered flashbang arguments to avoid a persistent runtime

Runtime Fixes, August 12 2022

---

code/_onclick/other_mobs.dm
code/datums/hud.dm
code/game/machinery/computer/arcade/orion_trail.dm
code/game/objects/effects/landmarks.dm
code/modules/antagonists/swarmer/swarmer.dm
code/modules/hydroponics/beekeeping/beebox.dm
code/modules/mob/living/simple_animal/bot/bot.dm
code/modules/mob/living/simple_animal/eldritch_demons.dm
code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
code/modules/mob/living/simple_animal/hostile/bees.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
code/modules/mob/living/simple_animal/hostile/mecha_pilot.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/shuttle/special.dm

Fixes some issues that prevented:
- All mobs from GCing (/datum/atom_hud not cleaning up after itself)
- Hostile mob targets from GCing (target variable not being cleared on target qdel)
- Simplemobs/bots from GCing (radio/access_card being qdel'd but not nulled)
GC on live is currently 400ms/tick.

Fix mob harddel/GC issues

---

_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

This PR changes the RockSprings and RockSprings-upper Z-levels to include an all-new prison dungeon. This dungeon has a mix of raiders and renegade mobs with unique names, all added to the "Powder" faction. It also makes better use of a considerable portion of the map on RockSprings.
This creates a new dungeon that supports AI guards for a Powder Ganger faction.
- [ x] You tested this on a local server.
- [ x] This code did not runtime during testing.
- [ x] You documented all of your changes.
:cl:
add: New two-level prison
add: Secret megafauna dungeon in Rock Springs
add: New secret chainsaw spawn
del: Removed overpass
del: removed raider shack where prison is going
tweak: Moved another raider shack north of the river, keeping it in place.
/:cl:

Creates new federal penitentiary in Rock Springs

---

code/modules/fallout/turf/ground.dm
code/modules/power/apc.dm

Fixes wasteland plants hard-deleting because of desert/mountain turfs.
Fixes APC power to the BoS bunker, in my testing.

Fix harddels and APC power

---

code/modules/research/techweb/_techweb.dm

Hotfix for the missing techweb causing runtimes.

Fix missing Enclave techweb

---

code/game/machinery/_machinery.dm
code/game/machinery/doors/door.dm
code/game/objects/structures.dm
code/game/turfs/turf.dm

Fixes noclip but this is the fix that I actually know works.
Also fixes some more runtimes with that PR agh.
Also fixes shooting through doors which I DIDN'T CAUSE BTW.

Fix noclip, but like, for real this time

---

code/__DEFINES/dcs/signals.dm
code/controllers/subsystem/idlenpcpool.dm
code/controllers/subsystem/matchmaking.dm
code/controllers/subsystem/npcpool.dm
code/datums/cinematic.dm
code/datums/components/_component.dm
code/datums/components/area_sound_manager.dm
code/datums/components/combat_mode.dm
code/datums/components/crafting/crafting.dm
code/datums/components/field_of_vision.dm
code/datums/components/storage/ui.dm
code/datums/elements/weather_listener.dm
code/datums/progressbar.dm
code/datums/weather/weather_types/rain.dm
code/game/machinery/autolathe.dm
code/game/machinery/deployable.dm
code/modules/antagonists/eldritch_cult/eldritch_effects.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/mob/login.dm
code/modules/mob/logout.dm

- Fixes weather sounds stacking.
- Fixes rain sounds never ending.
- Fixes reloading bench becoming non-interactive when its panel is opened.
- Fixes barricades not being barricades.

Weather, reloading bench, and barricade fixes

---

code/__DEFINES/_auxtools.dm

URGENT: This PR fixes every new gas mixture doing a filesystem operation, which is one of the slowest ops next to icons. This'll fix performance a LOT.

Fix gas_mixture/New being incredibly expensive

---

code/modules/mob/living/life.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Experimental tweaks for ListTargets and Life sleeping. Who knows if this'll help? But I was asked to try it anyway.

Fix ListTargets and Life sleeping/blocking.

---

_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
code/game/objects/items/melee/f13twohanded.dm
code/modules/jobs/job_types/bos.dm
code/modules/jobs/job_types/enclave.dm

- - -
Fixes:
- Venator spawn placed. Whoops.
- - -
Balance:
- Poor aim commented out for the moment on Scribes and Enclave Scientists. It didn't vibe with the server, and the introduction of such was to gauge a response.
- Proton Axe given a significant buff. Raised from 32 while on to 41. Throwing while on raise from 30 to 50.
- - -

Balance Pass #1

---

code/game/area/Space_Station_13_areas.dm
code/modules/fallout/areas/area.dm

Sorta urgent, because people keep complaining about it.
TODO: Add some sort of proper wasteland power system.

Fix power outages in areas with no APC

---

_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/holodeck/turfs.dm

This should resolve a number of problems with the prison and resolve at least one runtime.
:cl:
add: one new holofloor subtype, and a number of new instances of riveted walls to increase blast resilience of the prison.
tweak: Removes Supermutant Behemoth, replaces him with _three_ "strong-looking abominations" and centaurs in a unique faction.
del: Removed alien corpse spawner to resolve a runtime.
/:cl:

Reattempts prison repairs

---

code/game/objects/structures/watercloset.dm
code/modules/hydroponics/hydroponics.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm

Significantly buffs values relating to water and thirst, so that while non-water still provides an infinitesimally small amount of fluid for your system, standard water near immediately fills up the value.
Additionally, the special 'Kitchen Sinks' and wells provide purified water.
Also fixes the bug relating to crop watering.

Significantly Makes Thirst Easier

---

code/controllers/configuration/entries/general.dm
code/game/world.dm
config/config.txt

Reads the discord link from the config file instead of hard coding it.

---

code/__DEFINES/misc.dm

Simple, albeit aggressive change to drop values relating to blood trailing.
Will _probably_ work, but this is a five second PR and I'm half out of it.

Significantly 'Nerfs' Blood

---

code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/suits/f13factionarmor.dm

Updates armor values for all helmets. Also further tweaks some values based on gameplay.

Legion balance pass: The Second (Also fixes helmet values)

---

code/modules/clothing/suits/f13factionarmor.dm
code/modules/clothing/suits/suit_fashion.dm

Gives the field coats actual protection and adds pockets to standard/senior/headscribe robes.

Fixes robes and fieldcoats

---

code/modules/projectiles/guns/ballistic/rifle.dm

I FUCKED MY MASTER MAKING THIS EMERGENCY FIX

---

code/modules/clothing/suits/f13factionarmor.dm
code/modules/projectiles/guns/ballistic/shotgun.dm

pancor jackhammer semi auto fire delay 2.85 < 0
elite riot armor slowdown 0.1 < 0.01

Nerf Elite Riot Armor and Pancor Jackhammer

---

code/modules/mob/living/simple_animal/hostile/f13/centaur.dm

Abominations inject you with FEV, turning you into a simplemob and round-removing you.
Who thought this was a good idea.
Round removal is bad. Round removal by mobs is horrible.

[Salt] Removes Funny Round Remove Mechanic In Mob That Shouldn't Have Been Used

---

code/modules/clothing/masks/miscellaneous.dm

- - -
Permits the facewrap, when lowered, to show flavour text.
- - -

Facewrap Identity Crisis

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
code/modules/clothing/suits/f13suits.dm

replaces radiation suits with hazmat suits, allows hazmat suits to be put in bags, attaches the hood to the suit itself so you can toggle it from your hud, adds a hazmat suit to thematically appropriate areas.

Hazmat suit improvement

---

code/modules/clothing/suits/f13factionarmor.dm
code/modules/jobs/job_types/ncr.dm

Trail Carbine, .44 Box, .44 IND < Rangemaster, 7.62x51 mag x2
Trail Ranger armor slowdown 0.03 < 0.01

Trail Ranger is no longer the meta ranger loadout

---

code/modules/reagents/chemistry/reagents/other_reagents.dm
code/modules/reagents/chemistry/recipes/drugs.dm
code/modules/reagents/chemistry/recipes/medicine.dm

Fermichems were removed from fallout chems. There is not really anything else to say about it.
Hydrogen was balanced with its PH, so it does not ruin all recipes that use it.
Previously, you had to sit down and code dive even to know the basics of how to make fallout chems. That is, of course, not an ideal situation for the players and causes a lot of frustration. Even more, when fallout chems were the only ones that had to suffer with this.
:cl:
del: Removed fermichems on fallout chems + PH on hydrogen
/:cl:

fallout with PH

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Requested changes to remove the enclave armor, and everything that was a guaranteed spawn.
Guaranteed spawns are not supposed to be in the dungeon, from what I got told

Rockspring dungeon changes - Requested

---

code/modules/fallout/areas/area.dm

I was asked to allow power in the dungeon since it was causing trouble that there was none. 
This made it impossible for people to use the console to call the elevator.
:cl:
/:cl:

[BUGFIX] Bunker power

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm

It adds an ore box that was removed from the BoS
And adds some walls and doors at the venus trap place that always kills the NCR.
:cl:
/:cl:

Barrier for the venus trap + Ore boxes for BoS

---

code/__DEFINES/storage/_storage.dm

DO NOT MERGE THIS UNTIL IT PASSES LINTERS.

Fix linter false-positive

---

code/modules/mob/living/carbon/human/species_types/jellypeople.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm

:cl:
checks for perk and then heals slimes from toxin damage
/:cl:

Toxin now heals slimes of burn and brute but not humans

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Mostly Remaps the Lab and Armory slightly, Adds colour coding to the doors and renames most doors. Nothing changed balance wise as much as I can tell, just removed some bunks, extended the RnD lab and swapped where the scribe office is to add a window between the lab and the armory.

BoS Map Minor changes.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/modules/clothing/under/accessories.dm
code/modules/jobs/job_types/bos.dm
code/modules/projectiles/ammunition/energy/laser.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/projectile/beams.dm

The high elder sends their support and sends:
The paladins finally have some mid-tier weapons, including weapons they can use for stealth actions + a pretty good semi-automatic option. Variety!
A slight upgrade on the laser weapon, as well for the regular paladins
A new laser option was added for the head paladin.
Some knight pins were added as part of the announcement that was made.
The baron gets a weapon to fit the theme of the brotherhood of steel weapons: a new weapon called the Walkers Recharger Pistol

Brotherhood outfit changes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Labfixes Mapping

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Fixes RnD server location and moves some stuff around in the head scribe office

More Mapping Fixes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Just a change to some terf that was visible with mesons, not a huge deal.

Low Priority fixes.

---

code/modules/jobs/job_types/enclave.dm

Give the Gunny a command radio and megaphone for maximum yelling.

Loudening of the Gunny

---

code/modules/food_and_drinks/recipes/drinks_recipes.dm
code/modules/reagents/chemistry/recipes/medicine.dm
code/modules/reagents/chemistry/recipes/others.dm
code/modules/unit_tests/reagent_recipe_collisions.dm

See above. Will also include fixes for that once it's in.

Add a unit test to catch conflicting chemical recipe IDs

---

code/game/machinery/radio_management.dm

Makes radio terminals dense
Consistency

Makes radio terminals dense

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm

Closed my previous PR because I had to manually merge it with Carl's khan changes, here are the screenshots of the changes.

BoS Topside Overhaul

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/modules/clothing/head/f13head.dm
code/modules/clothing/suits/f13armor.dm

It was removed with the knight-commander locker. Now, it's added back in.
Huzzah.
:cl:
/:cl:

Knight commander armor

---

code/modules/reagents/chemistry/recipes/drugs.dm
code/modules/reagents/chemistry/recipes/medicine.dm

A few stimpack recipes were added since the super stimpack needed synthetic blood while the normal stimpack required blood.
Now you can make both with synthetic blood and normal blood.
Code dev request: removed the code instead of *\  /* as requested by a head code to clean up the code.

[BUGFIX] - Stimpack recipes for synthetics and humans

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

As title, re-adds sheriff doors in bighorn and adds the khan spawns. Fixes the stairs in the BoS bunker

Map Fixes to Bighorn and BoS Bunker.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Reverts sunset-wasteland/sunset-wasteland#449

Revert "Map Fixes to Bighorn and BoS Bunker."

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

- - -
Yuppers. As it says on the tin.
Permits you to go upwards in the Brotherhood's topside location.
- - -

Fixes Stairways

---

modular_sunset/code/modules/client/loadout/head.dm
modular_sunset/code/modules/client/loadout/suit.dm
modular_sunset/code/modules/client/loadout/uniform.dm

Removes free access to deputy's armor, helmet and uniform.
With original town's roles back there's no more need to keep them freely available anymore.
:cl: Anonymous
tweak: Deputy's armor, light helmet and uniform are no longer accessible freely in the loadout (since Town's roles are back).
/:cl:

Reverts Deputy's armor, helmet and uniform loadout access

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Adds Lisa, the corgi, to the Enclave bunker. Also gives her a little dog bed, a crayon, and a tennis ball.
Infantry vibes. We have something to fight for now.

Lisa da dawg

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

The enclave can't really go outside risk-free, so they need a place where they can salvage wreaks in peace.
Plus the ore silo boards that I forgot to add.
:cl:
/:cl:

Enclave: A rubbish place for NML and missing ore silo

---

code/game/objects/items/devices/geiger_counter.dm
code/modules/fallout/obj/decals.dm
code/modules/fallout/obj/structures/barrel.dm

Geiger counters actually measure the radiation hitting whoever is carrying them now!
They also detect radiation from goo puddles and radioactive barrels.
Knowing when you're being irradiated is sorta important in Fallout.

Makes geiger counters work

---

code/modules/jobs/job_types/enclave.dm

give enclave chameleon gas mask
it hide their voices and face, this also disguise their voice as whatever their agent ID was set to
:cl:
add: Added chameleon mask to enclave loadout
/:cl:

enclave with chameleon gasmask

---

code/modules/mob/dead/new_player/sprite_accessories/ears.dm

Fixes the missing Ears from the character creation screen. 
Adds missing ears. Such as Big Wolf, Elf, Jellyfish and Elephant ears to the main fork.
Basically. Lets players LARP as Elf Girls and Boys again
Missing icon path's for /datum/sprite_accessory/ears/human/ items. So I added them individually to those which did not appear ingame.
Tested the Elf Ears. They worked. Then I added the missing icon = 'modular_citadel/icons/mob/mam_ears.dmi' to each path where it wasnt' appearing ingame.
:cl:
fix: Character creation Ears
/:cl:

Fix ears.dm

---

code/modules/jobs/job_types/enclave.dm

Chameleon mask in pocket instead of bag
Some people may have item in their bag which make the mask not spawn in it properly so these role had their mask adjusted to spawn in their pocket instead.
:cl:
tweak: mask in pocket instead of bag
/:cl:
issues #484

moving the enclave mask from bag to pocket

---

code/game/objects/items/stacks/medical.dm
code/modules/hydroponics/grown/ambrosia.dm
code/modules/reagents/chemistry/recipes/medicine.dm

Nerfs meshes chem creation from 15 > 5
Buffs sutures chem creation from 1 > 5
Balanced, as all things should be

Sutures and Meshes

---

code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/head/jobs.dm
code/modules/clothing/suits/armor.dm
code/modules/clothing/suits/f13armor.dm
code/modules/clothing/suits/f13factionarmor.dm
code/modules/clothing/suits/f13suits.dm
code/modules/clothing/suits/heavy_armor.dm
code/modules/clothing/suits/light_armor.dm
code/modules/clothing/suits/medium_armor.dm

As title, not much more to say, went through armor and removed wound armor. The only thing I kept was helmets having 40 wound armor, so people actually have an incentive to wear their helmets to stop their brains from being painted across the pavement.

THE RECKONING (Removing wound armor, heavy armor keeps 10, PA-level gear gets 20)

---

code/modules/projectiles/guns/ballistic/automatic.dm

DAMAGE 19 < 21
ARMOR PENETRATION 15% < 0
FIRE DELAY (SEMI) 2.7 < 6
FIRE DELAY (AUTOMATIC) 1.75 < 2.7

R84 UNFUCKENING: THE SEQUEL 

---

code/game/communications.dm
code/game/objects/items/robot/robot_upgrades.dm
code/modules/keybindings/keybind/living.dm
code/modules/mob/living/living_mobility.dm
code/modules/mob/living/silicon/robot/inventory.dm
code/modules/research/designs/mechfabricator_designs.dm
code/modules/research/techweb/all_nodes.dm
code/modules/research/techweb/nodes/robotics_nodes.dm
modular_citadel/code/modules/mob/living/silicon/robot/robot.dm
modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm

- Adds a Radio Transceiver upgrade, unlocked from the start, which grants extra radio channels to cyborgs. To use, slide an ID on it to inherit the appropriate faction radio channels.
- Fixes medical upgrades not applying to Medihounds and Medical Assaultrons.
- Fixes the "Rest" hotkey not working for dogborgs.
- Gives Security K9s an AER9, unlockable with the Illegal Module upgrade.
Oversight fixing and balancing is good. Cyborgs having access to their respective faction radios is also good.

Even more fixes and additions to cyborgs

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm

- - -
Corrections:
- Provides the Mountain Complex with communications.
- Removes some erroneously bolted doors.
- - -

Mountain Complex Comms

---

_maps/pahrump.json
code/modules/jobs/job_types/bos.dm

- - -
As it says on the tin.
- - -

Corrects Lacking Trait for New Map

---

_maps/pahrump.json
code/modules/jobs/access.dm
code/modules/jobs/job_types/bos.dm

- - -
Enables Job Bans for Enclave. Properly. Probably.
- - -

OH GOD OH FUCK

---

code/game/objects/items/storage/f13storage.dm
code/modules/jobs/job_types/enclave.dm
code/modules/projectiles/projectile/beams.dm

Makes like three small changes. One is a nitpick, one is by request from badmancarl, the other is me trying to fix something that may or may not have already been fixed.
Ration change scratches an itch and makes it make more sense, second one helps the gamma gun not be so shit, third actually gives Enclave scientists the correct ammo for the gun they spawn with.
:cl:
tweak: gave the ranger lunch ration an actual lunch entree
balance: buffed gamma gun rad damage by 50 (by request of badmancarl)
fix: gives enclave scientists the correct ammo type for their gamma guns

Small changes

---

code/modules/mob/living/silicon/robot/robot.dm

should work
if this doesn't i guess the 10 bucks are invalid IDK

Removes Dogborg from Module Selection [ADMIN EDIT]

---

code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/projectile/bullets/shotgun.dm

**Caravan Shotgun**
RECOIL 1.55 < 0
**Winchester Widowmaker**
RECOIL 0.55 < 0
**Browning Auto-5**
FIRING DELAY 3.95 < 5
RECOIL 0.55 < 0
**LEVER ACTION SHOTGUN**
SLOWDOWN 0.25 < 0.3
EXTRA DAMAGE 1.8 < 0
RECOIL 1.35 < 0.5
**WINCHESTER CITYKILLER**
RECOIL 1.75 < 1.25
**PANCOR JACKHAMMER** (an awful thing)
RECOIL 1.35 < 1
**NEOSTEAD 2000**
RECOIL 1 < 0
**12 GAUGE BUCKSHOT**
WOUND BONUS 10 < 35
BARE WOUND BONUS 55 < 75

SHOTGUN BALANCE PASS 2: LIVE GAMEPLAY EDITION

---

code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/suits/f13factionarmor.dm

Vex armor has always been the worst of the legion armor, simply because of the fact that it has been slow.
Now, they have to compete against the NCR heavy trooper, so they get a slight buff to make it as fast as using the legion veteran armor.
Bullets 37 > 42
bomb 25 > 30
bio 20 > 30
rad 20 > 30
fire 25 > 30
slowdown = 0.12 > 0.05
:cl:
server: …

Vex armor changes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/jobs/job_types/bos.dm

Increased the number of paladins by one
Decreased the number of guaranteed power armors to 1, instead of the usual 4
For the rest of the normal slot. An RNG system that heavily favors combat rifles and mid-tier energy guns is made.
It could potentially get you 2 power armors or a good melee weapon. But, the chances are very slim.
:cl:
server: …

The vault, the paladin

---

code/__DEFINES/dcs/signals.dm
code/datums/elements/flavor_text.dm
code/datums/mind.dm
code/modules/client/preferences_savefile.dm

What it says on the tin.
Code taken from hyper.
Also fixes a fucky someone made when loading silicon flavor text, now it will load correctly between rounds.
Makes it so silly cones get to have descriptions.

Fixes Silicon Flavor Text And OOC Info Not Appearing On Borgs

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Redone to be mergable, same as last time, sorry for lack of description but I already did a massive writeup on https://github.com/sunset-wasteland/sunset-wasteland/pull/457

Bos Mapping

---

code/modules/clothing/suits/f13suits.dm

Fixes follower hoods from not hiding hair/ears etc.

Follower Hood Fixes

---

_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Fixes a second floor not having a roof.

Roof fix, rocksprings orchard

---

code/modules/smithing/anvil.dm

Comments don't match the actual recipe, this can lead to people using the code to smith getting screwed over because of it.
:cl:
tweak: Fixed some incorrect wording in the smithing recipe code, wah.
/:cl:

Fixes some incorrect words

---

code/modules/reagents/chemistry/recipes/others.dm

Lets you boil water/boiled water further to turn it into salt. People kept asking me to do this because there's no consistent source of salt without using chemistry.

Getting salt from water.

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm

Enclave does not have any clothes to deal with the cold weather.
Now they do, with fresh, lovely clothes to wear.
12 winter suits and boots
Some internal gear (6 and a tank)

Enclave: It's so chilly outside

---

code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

Ghoul Balance Speedmerge

---

code/modules/fallout/misc/gang_items.dm
code/modules/fallout/misc/gangs.dm

Gang tools are added, changed, and done a lot better.
A bunch of weapons can now be bought, with some emergency medical equipment (they are very expensive)
A melee weapon can be bought.
Caravan shotgun and varmint can be bought for cheap.
Randomized ballistic guns can be bought. It becomes expensive depending on the tier.
Randomized energy pistol.
Grenades have been fixed, firebombs added, and HE grenades/dynamites have been standardized to what we use.
A chem machine kit. That does not give you anything other than the boards. (Also extremely expensive, just go find a medical setup instead)
Magazines were given to the various guns.
Fixed the undocumented changes. For the two items.

Gang tools my beloved

---

code/game/objects/items/tools/weldingtool.dm
code/modules/power/cable.dm

Properly removes the synth heal limit rather than disabling it with a hack.
Remove it entirely or not at all.

Remove synth heal limit (properly)

---

code/modules/jobs/job_types/ncr.dm

Gives the 10mm SMG ranger loadout the extended magazines, which are the ones the SMG fit.
Fixes a very old oversight
:cl:
fix: 10mm SMG ranger loadout now gets the correct magazines.
/:cl:

Gives the 10mm SMG ranger loadout the correct ammo

---

code/game/machinery/computer/card.dm
code/modules/jobs/access.dm

It makes people able to use the ID computer again.
Changes to the get_all_jobs() were requested by Carl.

ID computer fix

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/shuttles/Brotherhood_of_Steel_base.dmm
code/modules/fallout/obj/structures/mob_spawners.dm
modular_citadel/code/modules/client/loadout/__donator.dm

!Mob spawner changes!
The mob spawner has been changed to stop it from being a gun spawner. Yeah, you could mass-print guns with it.
The sound for the tunnel has also been reduced, so your ears won't be blown up by 3 tunnels.
Enclave Added:
Xenobiology cold room
Console for xenobiology and basic disk
Slime processor
One monkey cube box
Second locker for the winter gear
Research documents for people that want to make weapons.
Larger virology
Basic mining gear
Destroyed car park with ghouls to protect it
Part replacer
Brotherhood of steel:
The "elevator" has been given makeup to look like a shuttle
Paladin room.
advanced workbench, like the rest of the tech factions.
Smaller toilets
General changes:
Made some small changes to the map so that the shuttle does not get hindered by the various …

Train shuttle, enclave base changes

---

code/modules/reagents/chemistry/recipes/toxins.dm

Simply disables the recipe for zombie powder and sulf.
Woe be upon ye.

Disabling ZP

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
modular_citadel/code/modules/client/loadout/uniform.dm

- - -
Map:
- Adds NML signs outside of Casper.
- - -
Loadout:
- Readds gear harnesses to uniforms.
- - -

Casper NML signs. Minor touchups.

---

code/__HELPERS/global_lists.dm
code/_globalvars/lists/objects.dm
code/controllers/subsystem/ticker.dm
code/game/objects/effects/decals/cleanable.dm
code/game/sound.dm
code/modules/integrated_electronics/subtypes/input.dm
code/modules/lighting/lighting_setup.dm
code/modules/power/lighting.dm

- Removes a bunch of unnecessary stoplags/spawns/etc.
- Does a bunch of micro-opts.
- Moves some code in spawn()s in Initialize into LateInitialize instead.
- Rewrite how blood is cleaned by rain to be far less expensive.
Attempting to decrease startup cost and lag caused by rain.

Performance tweaks

---

code/modules/station_goals/dna_vault.dm

Updates the DNA vault so it's usable, lowers armor value of the bone reinforcement thing
Kind of redundant to have a vault you cannot physically fill up DNA point wise
:cl:
tweak: Changed default values for the DNA vault
tweak: Changed reinforcement upgrade armor from 30 to 15
/:cl:

DNA Vault update

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

A bunch of map edits for the brotherhood of steel (mostly for the castellan room)
You can now LOCK the doors in various bedrooms.
- A new library area
- Washing machine in the gym
- Sauna and pool
- some changes to the picnic area
- A hidden bar area
- Some changes to behind the house

BoS area changes and locked rooms

---

code/modules/projectiles/guns/ballistic/gunpart.dm
code/modules/projectiles/guns/ballistic/modifiable.dm
code/modules/projectiles/guns/ballistic/revolver.dm

- - -
Temporary Removal of Modifications for Revolvers
Temporary removal of burstcams.
- - -

Modification Hotfix

---

code/modules/projectiles/guns/hoboguns.dm

Didn't realize something very blatant. Ignore this.

Pipegun Correction

---

code/modules/projectiles/guns/ballistic/automatic.dm

**14mm SMG**
+SPREAD
+RECOIL
+FIRERATE
**P90**
-SLOWDOWN
**VERMINKILLER**
+AP
**RATSLAYER**
+AP
**ALR-15**
LOL NO
**SCOUT CAR.**
-DAMAGE
**MARKSMAN**
+SLOWDOWN
+AP
**COLT MONITOR**
-DAMAGE
+AP´
**DKS SNIPER RIFLES +VARIANTS**
+DAMAGE
+AP
**RANGEMASTER**
-BULLET SPEED
**FN FAL**
-BULLET SPEED
**LIGHT MACHINE GUN**
-DAMAGE
-Police Rifle half-viable, able to compete with similar automatics

ESSENTIAL POST UPDATE TWEAKS, PART 1

---

code/modules/jobs/job_types/admin.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/minigun.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/rifle.dm
code/modules/projectiles/guns/ballistic/shotgun.dm

Adds a manner of damage or penetration adjustments to every gun that reasonably needed it.
Also, removes some redundant shit from the code.

FULL FORCE FORWARD (GUN REBALANCE PATCH)

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm

Fixes armory access, currently the windoor does not use the same access codes as the two airlocks, resulting in privates climbing over the table.
I assume this was not intended as a way to gain access.
:cl:
fix: fixed Enclave armory access
/:cl:

Fix Enclave Armory access

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

This pull request adds three new Vertibird landing areas, two in Rock Springs (SE, and Center of map south of Legion) and a landing area in the small wood area west of north bunker.
With teleport slimes removed the primary means of fast Enclave transportation is the Vertibird.  The landing areas are well known and players from other factions will immediately begin checking them on Vertibird activity.  This PR adds more places to check, and more options for landing.
:cl:
add: 3 new Vertibird landing areas
/:cl:

New landing zones

---

code/modules/projectiles/guns/ballistic/automatic.dm

Combat rifle changes, as requested by Carl
Attachments unlocked
AP has been given (0.1)
It still has a 0.25 slowdown, making you slower than most other standard weapons.

BoS combat rifle changes

---

code/modules/jobs/job_types/enclave.dm

This pull request adds the TRAIT_RESEARCHER trait to the Enclave Pilot Officer, allowing them to use the research console like the sergeants. 
It is beneficial for solo or low pop enclave as it allows the Pilot Officer to conduct initial research while they wait for other players to potentially join, it also allows them to entertain themselves on those solo-clave rounds.
:cl:
tweak: added research console access to Enclave Pilot Officer role
/:cl:

Add TRAIT_RESEARCHER to Pilot Officer

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/minigun.dm

**Police Rifle**
DAMAGE - 16 (From 19)
ARMOR PENETRATION - 30% (From 45%)
**Minigun**
DAMAGE - 10 (From 12)

Police Rifle nerf

---

code/game/objects/items/storage/survivalkit.dm
code/game/objects/structures/stairs.dm

NO MORE SURVIVAL STACKING OR STAIR SMASHING

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Replaces an invisible box and a bunch of mags that aren't intended to be present.

Minor EB Corrections

---

code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm

- - -
Significantly reduces deathclaw speed.
Removal of deathclaw charge, for now.
- - -

Deathclaw Nerfs

---

code/modules/jobs/job_types/enclave.dm

Replaces the peacekeeper uniform on internal security with an officers one. Considering all IS are officer ranked, this is thematically appropriate.
Muh immersion
:cl:
fix: Internal security get the correct uniform
/:cl:

Internal security given officers uniform

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm

give the enclave stun batons, spare pipboys and a medal box in the LT office
give the enclave stun batons, spare pipboys and a medal box in the LT office. doesn't hurt the balancing.
:cl:
add:give the enclave stun batons, spare pipboys in the armory.  and a medal box in the LT office
/:cl:

baton pipboy n medal box for enclave

---

config/in_character_filter.txt

Adds a few words to the IC-game filter.
Heard about a player getting banned for saying n**ga, it should've been blacklisted by the IC-filter. This change will help enforce a High-roleplay standard and stop players from getting banned on things they might say on a whim.
:cl:
add: Added a few words to the filter
/:cl:

Adds to ic-filter

---

code/modules/movespeed/modifiers/innate.dm

We don't need PA at twice the usual speed
It reduces the DNA vault speed bonus to something not broken
Honestly, double the normal running speed while on PA sounds funny but it's also broken as all hell. This should make them only 20% faster, I haven't tested it because I'm at work. If it's still too fast, easy to lower further, if it breaks, Byond can burn in a fire.
:cl:
code: changed dna vault speed define
/:cl:

Reduce DNA vault speed bonus

---

code/modules/reagents/chemistry/reagents/other_reagents.dm

Changes the taste of dirty water from "chalky water" to "foul, brackish water", to differentiate it from the taste of boiled water.
First PR in like 3 years, wasn't sure how to format it.

Changes dirty water taste

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm

No more spying on the enclave
- Adds all the enclave cameras in xenobiology into a network

Enclave camera problems

---

code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm

Gives Legion Forgemaster and NCR Logistics Officer knowledge of G&B parts 1, 2, 3, and 4.

Give dedicated faction gunsmiths (Forgemaster, LO) the knowledge to make attachments and parts

---

code/modules/fallout/reagents/medicines.dm

Drastically nerfs Hydra's turbo health regen when you get wounded until the devs or a contributor finds a solution to how to make it properly cure wounds.
Hydra isn't a Notch's Apple anymore, let's hope it works.
:cl:
tweak: Drastically reduces Hydra's health regen after taking a wound.
/:cl:

Hydra nerf

---

code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm

basically turns toxin healing into a proper powder alternative rather than a supplement, also makes claws just a little slower but still extremely fast
:cl:
/:cl:

Nerfs claw speed by 0.2 and makes toxins a little more viable

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/fallout/areas/area.dm
code/modules/jobs/job_types/bighorn.dm
code/modules/jobs/job_types/followers.dm

Cleaned up the commits, used Map Merge 2 to actually merge the map properly. Adds a power plant to Bighorn, adds a construction area, sets Bighorn, the Followers, and Bighorn Underground to require power, adds access to Followers and Bighorners, puts the Schoolhouse on the Follower Grid, changes the Schoolhouse to match Follower construction.
Take two on the power-plant PR. This time done far more cleanly. Thank you, Carl!
I'll be honest, it's more a step in re-adding engineering as a whole. It means the town will require power to keep the lights on, and be able to produce it instead of relying on a magical infinite source. May have more meaning as more of the Wasteland is given it's own power-grid. Baby-steps, though! It's also my first foray into proper mapping.
:cl:
add: Added a …

Bighorn Power Plant (Properly, this time)

---

code/modules/clothing/under/accessories.dm
code/modules/jobs/job_types/bos.dm

Requested pin for roleplay
- Added a squire pin for the paladin kit

Squire pin

---

code/modules/surgery/tools.dm

now it fits inside your pouch and spare a headache of putting all advanced surgery tool in one pouch. even your beloved searing drill!
For Support (preferably medical roles for NCR/BoS/Enclave) to practice medicine in the field... now with less messy backpack with searing tool properly fitting in your "tools" pouch!
:cl:
Change the size of searing tool to fit in a survival pouch. That's pretty much it.
/:cl:

Fix searing tool size to fit in survival pouch

---

code/datums/components/storage/concrete/pockets.dm
code/modules/smithing/finished_items.dm

bootable durger..... forged dagger bootable...why? always should of been.
:cl:moribund
durger
/:cl:

Durrgurrr....bootable forged durger

---

code/modules/fallout/reagents/teas.dm
code/modules/food_and_drinks/recipes/drinks_recipes.dm
code/modules/hydroponics/grown/agave.dm
code/modules/hydroponics/grown/buffalogourd.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/recipes/medicine.dm
code/modules/reagents/chemistry/recipes/others.dm

this was two days of work. it was painful and gave me so...so many issues. it adds tribal epi, tribal mannitol, a slime friendly heal from the plant itself and a new chem for rapidly purging chems and capping tox lose to deal with OD's and purging excessive venom. fix's a few temperature based issues with water as well. im tired...taking a break after this one...had too write 2 new chems
* changes the chems in buffalo gourd since the plant sucked. new chem exclusive to it. symbiotic algae. its weaker than omni. .75 heal for tox/oxy/brute/burn and is slime friendly so thos asshole snowflakes can have a plant heal
*buffalo gourds can now be juiced for buffalo juice. a 30u OD epinephrine for tribals and the legion. exactly the same as normal epi for stabilizing people after defib -slime …

Plant/chem tweaks - two new chems

---

modular_citadel/code/modules/client/loadout/uniform.dm

This does not actually fix the runtime I wanted to fix, but it fixes an error I discovered trying to debug the runtime I actually want to fix.
You can now select female merc, and female doctors outfits from the loadout screen.
:cl:
fix: fixed female merc and doctor outfit paths
/:cl:

Fix loadout uniform bug

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Accidentally placed a nuke disk.

Whoopsies, speedmerge.

---

code/game/objects/items/granters.dm
code/modules/jobs/job_types/legion.dm

Enables the Priestess of Mars Orator the use of alchemy tables.

Teachings of Mars for the Priestess loadout

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
code/game/objects/effects/spawners/f13lootdrop.dm

This pull request adds FEV to the `"good dungeon science loot"` list, and replaces all FEV bottles and specific spawns with this loot spawner.
The list has been modified to have a 45% chance of spawning FEV.
20% of FEV
20% of Curling13
5% of FEV-II
When combined with the replacing of FEV spawners with this list, this works out to _probably_ the same amount  of FEV per round, of about 4 or 5 bottles on average.  These bottles are scattered in the high-tier medical drops where FEV would usually be found anyways.
What is important, is you could have 4-5 bottles, 2, 0, or 9
But these are outliers, and you should expect 4-5.
Apparently people are being randomly searched in the wastes like baldies on red-alert if people can't catch all the bottles like they are pokemon.  This has gotten bad …

Random FEV locations and quantities

---

modular_citadel/code/modules/client/loadout/head.dm
modular_citadel/code/modules/client/loadout/neck.dm

Template for the BOS to have items added.
Items added.

loadout and BOS item template

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/jobs.dm

Gives Follower Guards the ability to choose between an engineering, mining, or combat loadout. Rebrands them as 'scholars', and gives them traits to match. Now they have more reason to work as field workers.
Also hotfixes a few access things.
Follower Guards are in a bit of an awkward spot now since Bighorn now has it's own defense force. This clears up some of the redundancy by giving them both a unique combat loadout (Hunting shotgun? Really?), and more they CAN do, giving them the ability to serve as field agents for the Followers... But no medical ability.
Also fixes Follower Admin access, and replaces the single weird bar door with a functional one.
As per the discussion in Suggestions, it's a much needed upgrade to Follower Guards. Renames them to Follower Scholars as well, to both …

Follower Guard Overhaul

---

code/datums/materials/_material.dm
code/game/objects/items/stacks/sheets/sheets.dm
code/game/objects/objs.dm
code/modules/antagonists/bloodsucker/objects/bloodsucker_lair.dm
code/modules/fallout/reagents/medicines.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/paperwork/paper.dm
code/modules/reagents/chemistry/reagents/drug_reagents.dm
code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
code/modules/reagents/chemistry/recipes/pyrotechnics.dm
code/modules/unit_tests/_unit_tests.dm
code/modules/unit_tests/reagent_names.dm

Fixes an issue where some chems would fail to work in certain scenarios.
There's some TG issue about it I'm too lazy to find.

Add reagent name collision test

---

code/modules/clothing/suits/f13armor.dm

hey why does the 25% slowdown armor top out at 40/40/40/25
also nerfed light plates

nerf armor kits

---

code/modules/projectiles/guns/ballistic/pistol.dm
modular_citadel/code/modules/client/loadout/__donator.dm

buffed the pistol whipping damage for the unique pistol from 12 > 17
fixes the armor sprite not showing
good for me yes-yes, not game breaking at all whatsoever.
:cl:
fix: the armor not showing proper sprites for it
balance: buffed the pistol whipping damage for it
/:cl:

keppler fluff fixes

---

code/datums/diseases/advance/symptoms/west_nya.dm
code/modules/antagonists/disease/disease_abilities.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/say.dm
code/modules/mob/mob_helpers.dm
fortune13.dme

This PR adds a new disease symptom "West Nya Virus" and an associated variable and say code.
The BOS has far eclipsed the Enclave in evilmaxing and this is an attempt to rectify that.
:cl:
add: Adds West Nya Virus
/:cl:

West Nya Virus

---

modular_citadel/code/modules/client/loadout/__donator.dm

Donator items for Two Wolves, a plundered paladin cape and gas mask.
Fluff request from Two Wolves
:cl:
add: Raxrus fluff for Juniper
/:cl:

Raxraus Fluff

---

modular_citadel/code/modules/client/loadout/__donator.dm

Apparently the cape from the previous fluff PR looked really bad with prime decanus armor.  This fluff item checks to see if the player is a Prime Decanus, and if so, spawns Prime Decanus armor that uses the Vex armor sprites, all attributes are otherwise the same.
PR was on request, apparently it looks better.
:cl:
add: Armor sprite change for raxraus
/:cl:

Raxraus fluff armor

---

modular_citadel/code/modules/client/loadout/__donator.dm

CKeys should not have `.`, this PR removes the list item for the ckey with the `.`
Code cleanup
:cl:
/:cl:

Fix ckey for mrsanderp fluff

---

code/game/objects/items/storage/lockbox.dm
code/game/objects/structures/crates_lockers/closets/secure/supplypod.dm
code/modules/cargo/supplypod.dm
code/modules/hydroponics/growninedible.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/power/solar.dm
code/modules/projectiles/pins.dm
code/modules/recycling/disposal/construction.dm

Fixes a bunch of invalid initialize overrides, some of which cause runtimes.
Currently uh. Goats runtime? My bad.

Fix invalid initialize overrides

---

code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/suits/f13factionarmor.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Raider armor has, in some way or another, been nerfed.
NCR armor has, in some way or another, been buffed. Again.
Ranger-Hunter armor now mimicks the stats of the Veteran Ranger's armor, with lower and higher resistances to lasers and melee respectively.
Raised wound armor for some of the highest roles.

More armor tweaks. Again.

---

code/controllers/subsystem/research.dm
code/modules/research/server.dm

This PR changes the enclave R&D server mine rate from 7 to 17, slightly more then doubling its research point generation.  It also moves research point generation to the unused mining variable of individual R&D servers, allowing for per faction research rates.
Despite the Enclave's stated role as the always valid boogeyman faction, the reality is that the Enclave is significantly research and logistically disadvantaged compared to the Followers and Brotherhood.  Unlike the Followers, the Enclave has no ability to trade roundstart for research papers.  Unlike the Brotherhood, there are no bunkers to run, and the Enclave population does not always support mining or local salvage in Casper.   The Enclave also does not have a resource train it can feed with golden apples from botany.  
This …

Enclave R&D changes + R&D server research point variables

---

code/modules/mob/living/carbon/human/species.dm

Apparently, there were no serious consequences for not eating.  This makes you go into critical stamina if you fall significantly below starving.  You will have to crawl to a vending machine and eat something to get back up.
I don't anticipate this coming up often, but it seemed like this was an oversight based on how the mood system worked.
:cl:
fix: You now need to not be starving to have stamina, you still will be unable to starve to death.
/:cl:

You need to eat

---

modular_citadel/code/modules/client/loadout/__donator.dm

This pull requests guts most of the items added in my initial fluff PR, while I argue that my fluff was by far not the most balance altering, it would come up in arguments.  The purpose of this PR is to remove "fluff" based arguments entirely from the minds of neutral third-part observers to dev-chat arguments.
Everything not a base level organ replacement has been removed.
In that the original list did not alter anything, removals from that list also should not alter anything.
:cl:
del: Removed all non base level organs from alffd's fluff list.
/:cl:

Prune alffd fluff

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

This PR removes the followers door exit button and adds a South to North unrestricted access flag to the door.
The button was broken, this allows use of the door to exit without any access, entry access is unchanged.  This should help people leave the followers clinic.
:cl:
fix: Broken followers exit button replaced with a South to North no access airlock.
/:cl:

Followers door exit fix

---

code/datums/explosion.dm
code/modules/mapping/map_config.dm
tools/ci/ci_maps.txt
tools/ci/run_server.sh

Fixes the default map config and the CI map config.
We should probably be testing that the map has no runtimes.

Fix integration tests not loading the map

---

code/controllers/subsystem/job.dm
code/datums/datacore.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/mob/dead/observer/observer.dm

Also makes follow a valid  verb again.
:cl:
add: Added follow verb, some admin helper verbs.
/:cl:

Adds a few admin helper procs (spawn character, despawn character)

---

code/modules/hydroponics/hydroponics.dm
code/modules/reagents/chemistry/holder.dm

This could've been done better this whole time, so I finally did it. I rewrote adding water to hydrotrays.
- Fixes not being able to add water to full trays.
- Fixes the transfer amount when adding water being doubled.
- Fixes water sometimes accumulating in the nutrient tray and not clearing.
- Fixes a missing space in the examine text.

Fix adding water to hydrotrays.

---

code/modules/fallout/obj/structures/mob_spawners.dm

My updated code was never actually in and didn't check for this anyway. My bad.
Fixes a bug.

Fix being able to seal nests with any stack

---

code/datums/wounds/_wounds.dm

Unit tests randomly fail because wounds don't delete properly. Oops.
Carl complained :(

Fix wounds harddeling

---

code/_globalvars/lists/maintenance_loot.dm
code/controllers/subsystem/idlenpcpool.dm
code/modules/clothing/suits/f13armor.dm
code/modules/fallout/resources/sheet_types.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
code/modules/vehicles/_vehicle.dm
code/modules/vehicles/wasteland/motorcycle.dm
code/modules/vehicles/wasteland/vehicle_fuel.dm
modular_citadel/code/modules/client/loadout/suit.dm

- Fixes mispathed punk armor kit
- Fix mobs waking up/aggroing through walls
- Rewrite FindTarget
- Fix hay recipes
- Fix ghosts interacting with motorcycles
- Modernize vehicle code
- Raise idling NPC pool to 4 second wait to avoid overlapping voicelines
Mobs waking up through walls SUCKS.
Otherwise, just fixes.

Misc. fixes, January 12 2023
