sunset-wasteland/sunset-wasteland

code/modules/projectiles/boxes_magazines/_box_magazine.dm
code/modules/projectiles/boxes_magazines/ammo_boxes.dm

Most improvised ammo bags had significantly more ammo than the sprite they share had icon states to support it. I refactored the code to account for this.
It's a bugfix.
:cl:
refactor: A variable that determines how the ammo items update their sprites has had a new option added, which the improvised ammo bag will now use to show the most full icon state it has until the stored ammo inside falls below a threshold of 8. This is done to account for ammo bags having a higher ammo count than their current sprite code and icon states support, which in turn caused the bags to be invisible.
/:cl:

Fixes a sprite issue with improvised ammo bags

---

code/modules/surgery/emergency_cardioversion_recovery.dm
code/modules/surgery/graft_synthtissue.dm

Makes it possible to perform Emergency Cardiovascular Recovery and Graft Synthtissue with Medium Surgery. Fixes a bug with GST resulting from fermichem's removal. Removes the time of death check from ECR.
Synthtissue grafting now works properly with the fermichem removal. Reviving an organ with chronic failure requires >80u of synthtissue in the patient's bloodstream, instead of the now-defunct grown volume.
Cardioversion recovery no longer checks for time of death, making it a true replacement for the defunct Cerebral Revival surgery and eliminating the necessity for players to call the "I'M DED PLS RESTART" vote if they die during low-pop.
Both surgeries now require mid-level surgery instead of the medical graduate trait, meaning that roles with access to the DC Journal of Internal …

Fixes some issues with ECR and GST surgeries

---

code/modules/jobs/loadout_ingame.dm

- - -
Simply comments out a line that shouldn't change anything, but seemingly does. Wacky.
TM this. If it doesn't fix your issues, I 'unno what to tell you, because everything ran smooth locally. It could very well be a server issue with such.

Prevents Critical Mass [READ]

---

code/datums/components/crafting/recipes/recipes_primal.dm
code/game/objects/items/storage/backpack.dm
code/modules/jobs/job_types/wasteland.dm

Spear quivers are no longer only craftable by tribals. Anyone with the materials can craft them. I've also fixed an oversight which caused crafted quivers to spawn with spears already in them, circumventing the need for a workshop to make them. Any spear quiver that spawns on the map or in loadouts is unaffected; the recipe creates a new, empty subtype.
Spear quivers and throwing spears are really simple weapons that should be attainable by pretty much anyone. Random wastelanders and legionnaires alike can find use for these weapons, and having something to hold them in that isn't a backpack is super handy.
:cl:
tweak: Spear quivers can now be crafted by anyone.
fix: Crafted spear quivers no longer spawn with spears already in them. 
/:cl:

Removes crafting restrictions on spear quivers, fixes an oversight

---

code/modules/clothing/shoes/f13.dm
code/modules/clothing/suits/f13armor.dm
code/modules/clothing/under/f13.dm

**Please note, that I wasn't able to test the code on _current codebase_ because I cannot localhost it for some reasons.**
It was tested on other similar codebase, however, and code works so far.
This "fixes" digitigrade legs for most (if not all, let me or devs know if I missed some stuff) FO13 clothing making them snap into plantigrade sprites temporally when worn. If clothing don't cover legs and/or feet, it probably allows digitigrade to be seen.
Make it less frustrating to constantly see "SUIT" error icons if you character is digitigrade.
:cl:
fix: Fixes "SUIT" error for digitigrades by temporally snapping their legs to plantigrade when related clothing is worn.
/:cl:

Clothing that don't have digi-adapted sprites should now snap digi-legs to plantigrade when worn

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Front gates were tied to NCR Leadership access instead of regular, now corrected.

fixed NCR base access hotfix

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

-Much better tiles for all Mass Fusion buildings
-Fixed nothing tiles beneath catwalks (now open space)
-Fixed some machines in the facility not being anchored
-Some decals and decor added
-Actually a button in the basement now to open the shutters

Mass Fusion Glowup

---

modular_sunset/code/mob/renegade.dm

Adjusted items Renegade class mobs drop to make fighting them more worth it considering their difficulty spike in comparison to regular raider mobs.

Renegade Mob Drop Adjustments

---

code/modules/mob/living/carbon/human/species.dm

Reverts sunset-wasteland/sunset-wasteland#77
This actually completely disabled homeostasis which I might have noticed if I had my eyes open when I was making this PR. Deepest apologies.

Revert "Disables sweating/shivering indicators"

---

code/controllers/configuration/entries/general.dm

Minimum round time changed from 2.5 hours to 5 hours.
Voting time increased by an additional 30 seconds. 
Cooldown between votes increased to 60 minutes.

Adjusted round timers.

---

strings/insult.json

Removed
-vore
-gaylord
-shitcurity
-comdom
-greytider
-tator
-lingbin
-cluwn
-monkey
Modified or fixed
-Cheesemonger spelling
-Knight-like from Captain-like
-Comdom to dummy
Added
-Bramin-sniffer
-Raider
-scum-sucker
-mutie
-headass
-dumbass
-ghoul
-Kitten looking ass, added with Kit8bits permission
Now get your @pick(nouns_body) off my lawn.
This is fun code, and would be easy to bloat up to ridiculousness, but I don't think it would hurt to add a few more insult bases some time in the future.  It's very funny.

Updated *insult list

---

modular_sunset/code/mob/renegade.dm

Rebalances the Renegade Meister variant, lowered projectile amount per burst, replaced rare pistol drop with PA trait book. Also drastically slowed down the movement speed for when it's player controlled.

Renegade - PA Variant nerf

---

modular_sunset/code/game/objects/sunsetmisc.dm

Changes the sandstorm event text slightly. 
Before : Sandstorm is coming to the area, decreasing overall visibility outside.
After : A sandstorm is coming to the area, decreasing overall visibility outside.
Before : Sand waft down around you like grotesque snow. The sandstorm is here...
After : The sand wafts down around you like grotesque, thick snow. The sandstorm is here...
And finally
Before : The sandstorm slows, stops. Another layer of sand to the ground beneath your feet.
After : The sandstorm slows before stopping. Adding another layer of sand to the ground beneath your feet.

Fixes the bad grammar on the sandstorm event text

---

code/modules/jobs/jobs.dm

Makes the Legion Venator role once more selectable after PR #95 disabled it.

Legion Venator role fix

---

code/modules/mob/living/carbon/human/species_types/ghoul.dm

pugilist said so
ghouls can now join the bos
lore, ig
:cl:
tweak: Ghouls can join the bos.
/:cl:

lets ghouls join MW bos per lore accuracy

---

code/modules/research/techweb/all_nodes.dm
code/modules/research/techweb/nodes/medical_nodes.dm

This should stop integration tests from runtiming, as it removes a non-existent surgery (pacification) from the experimental surgery tech node.
E-Z(er) coding.

Removes runtiming surgery type

---

code/modules/client/border_control.dm

Apparently, the bordercontrol file uses `WhitelistedCkeys` with a capital W, not `whitelistedCkeys`
Makes the BC use the right thing.
:cl:
server: Makes the BC file use the original db array
/:cl:

This is just silly

---

fortune13.dme
modular_sunset/code/modules/client/loadout/head.dm
modular_sunset/code/modules/client/loadout/suit.dm
modular_sunset/code/modules/client/loadout/uniform.dm
modular_sunset/code/modules/jobs/jobs_types/wasteland.dm

This one probably need a review.
Removes (modularly) Oasis' roles restriction for light security helmets, OPD/Deputy armor vest and ~~Black Mesa~~ security suit-and-tie. Plus, removes utility vest restriction. Also moves them to the general sections of loadout tabs.
Another thing, that PR adds, is "Gun Nut" spawn loadout/kit. Spawn with nothing, but turtleneck, fingerless gloves, boots and grease gun along with two spare magazines.
1. Oasis Police Force were replaced by Khans, however loadout items were still lingering in the loadout menu, with people unable to get them.
2. "Change the Ammo (Utility) vest in the Loadout tab from NCR to neutral. It's an ammo vest, anyone could find one."
3. It was suggested.
:cl: Anonymous
tweak: Remove roles restrictions to the Utility Vest, OPD (aka …

[MODULAR] Removes restrictions for certain clothing in loadout, adds new spawn loadout/kit for Wastelanders

---

modular_citadel/code/modules/client/loadout/__donator.dm

Mr.Sanderp's ckey was incorrectly written as "mrsanderp". This commit adds a period to correctly look for "mr.sanderp"

Fixes Mr.Sanderp custom loadout option

---

code/game/turfs/simulated/water.dm
code/modules/fallout/turf/ground.dm

Rewrites code for desert edge spawning to reduce lag.
Before, 43415 desert turfs would individually check each of their four cardinal neighbors, for approximately 173660 turfs checked. Each turf would be checked to see if it was a water turf (of which there are only 4245).
This PR instead makes water turfs check their adjacent turfs (of which there are about 16980) for desert turfs, meaning about 150,000 fewer turf iterations during the initial SSatoms initialize flush.
150,000 fewer iterations during startup sounds good to me!

Rewrites desert edge code to reduce init time

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/__DEFINES/footsteps.dm
code/_onclick/observer.dm
code/modules/mob/dead/observer/observer.dm

- Adds missing footstep sounds to bare, heavy, and clawed footstep sound groups—if we don't want them in those lists we should make sure they're not assigned to `barefootstep` or `clawfootstep` in the first place.
- Fixes observer movement spamming runtimes.
- Fixes invalid AIStatus value in RockSprings.dmm.
- Removes nonexistent id var override in Dungeons.dmm.

Several runtime fixes

---

code/game/objects/items/melee/f13onehanded.dm

- - -
Changes the E-Tool from a normal item size to a small, so it can be put onto belts. As you'd expect such to be possible. I 'unno. Minor change or whatever. I think this also permits some stupid stuff, as a consequence, but, again, it's so minor and more of a QoL change that it shouldn't matter.
- - -

E-Tool Assistance

---

code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm

-Legendary deathclaws now have 1500HP (up from 1200) and 55% AP (up from 50%)
-They will drop 6 individual pieces of deathclaw hide instead of the standard 2
-With a 37% chance, they will drop one deathclaw gauntlet when butchered, hitting for 28 damage at 100% AP.

Buffs Legendary Deathclaw and gives it a unique drop again

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/ballistic/automatic.dm

Add on-examine text to guns to show what attachments a weapon can take, as well as what attachments it currently has.
Currently supported:
- Gun lights
- Scopes
- Bayonets
- Suppressors
- Burst cams
- Recoil compensators
- Automatic sears
The descriptions given are the best I could manage after searching each of the attachments. If someone has better alternatives or would rather just have it only say what attachment it can take, just say so.
Removes some gross description-mutating code in favor of examine overrides.
General quality of life; lets players know what attachments a gun can take. I was asked for this on the Discord.
:cl:
add: Guns now state what attachments they have and can take on examine.
/:cl:

Show gun attachment info on examine

---

code/game/objects/effects/spawners/gibspawner.dm

Fixes #288. The initialize functionality of gib spawners got split into a separate proc, which meant they weren't being qdel'd on init. Now they are.
Buggy ghost objects on alt click are annoying and make the server look bad to players.

Fix gib spawners not deleting after spawning gibs

---

code/_globalvars/lists/maintenance_loot.dm

Fix #131 by removing an abstract pipe item from the trash spawn table.
An invisible item named 'fitting' is unfitting loot.

Fix abstract pipe fitting spawning in trash loot

---

code/modules/projectiles/gun.dm

Fixes issue 167 by qdel_nulling the zoom action button when the scope is removed; it's readded when the scope is readded.
Tested with all sorts of combinations of things, like moving while removing the scope, scoped in or out while removing it, dropping it and picking it up after moving it, etc. It all worked for me.

Fix scope zoom buttons persisting after removing a gun's scope

---

code/modules/jobs/job_types/legion.dm

-The game no longer forces you to be male when playing a Legion role. This is in accordance with lore for Forgemasters and the Orator. < This also means you'll have to get despawned if you join other roles as a woman, go jannies go
-Improved the forbids/enforces list and objectives list.
-Added suppressor to the Veteran Decanus' "Mark of The Heedful" loadout.

Legioning pt. 2

---

modular_citadel/code/modules/client/loadout/uniform.dm

The NCR fatigue shorts, named "NCR fatigue shorts" in game, were changed on The Wasteland to be named "NCR Rhodesian shorts" in the loadout. This is completely lost on people who don't immerse themselves in fascist chan memes, i.e. "normal people."
Rigbe merged code without actually fucking reading it, apparently. Rhodesia shit is a bad meme. Stop drooling over a failed army failing to prop up a failed state. You're not cool for doing it, you just spend too much time on /k/, which is the opposite of cool.

Make the NCR shorts loadout name match the item

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
modular_coyote/code/modules/mapping/map_transition_patch.dm

Some blue matrix tiles had incorrect destinations, usually off by only a few tiles, but one was actually missing an entire digit and would dump people in a closed telecomms compartment forever.
Also, adds a name and description to the blue matrix turfs to differentiate them from green matrix turfs, and explain how to use them.
Removes gay baby jail (winding up in a closed telecomms compartment). Also makes these transit turfs a bit less confusing.

Fix incorrect transition (blue) matrix destinations

---

code/modules/fallout/obj/explosives.dm

Due to faulty checks, flashlights were set off by mines. Rather than checking the activating atom, it was checking `usr`, which is always either null or a player—meaning it'd sometimes get false positives for mobs stepping on it when something like a light overlay entered its turf.
Not setting off mines and plushies with flashlights is a good change.

Port Coyote fix for mines being set off by flashlights

---

code/__DEFINES/dcs/signals.dm
code/__DEFINES/dcs/signals/signals_atom_movable.dm
code/datums/components/butchering.dm
code/datums/components/caltrop.dm
code/datums/components/chasm.dm
code/datums/components/infective.dm
code/datums/components/magnetic_catch.dm
code/datums/components/pellet_cloud.dm
code/datums/components/squeak.dm
code/datums/components/swarming.dm

Refactors all uses of the defunct `MOVABLE_CROSSED`/`MOVABLE_UNCROSSED` signals to use connect_loc/connect_loc_behalf and `ATOM_ENTERED`/`ATOM_EXITED`.
Fixes caltrops, fixes plushies, fixes a few other things no one cares about.

Fix caltrops, plushies, etc.

---

code/datums/explosion.dm
code/game/data_huds.dm
code/game/objects/items/melee/f13powerfist.dm
code/modules/client/preferences.dm
code/modules/mob/living/living_active_block.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/silicon/silicon.dm
code/modules/mob/mob.dm
dependencies.sh

- Bumps rust-g versions to see if it fixes an error with querying centcomdb.
- Fixes a null reference runtime in stop_active_blocking.
- Fixes the f13 powerfist throwing deleted mobs.
- Fixes explosions throwing deleted items.
- Fixes a broken keyword argument in run_armor_check.
- Fixes silicons runtiming from a missing SSD hud.
- Fixes a runtime from things that returned an empty examine result list.
- Fixes a runtime from spam-clicking on "remove marking".
Runtimes bad. The explosions one specifically gave us over 1k in a few seconds. TODO: Port SSexplosions.

Runtime fixes, August 13, 2022

---

_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/game/turfs/f13concrete.dm
code/modules/fallout/obj/structures/setpieces.dm
code/modules/pool/pool_drain.dm
fortune13.dme

This is semi-urgent.
- Drains cause massive runtimes.
- Mapmerge didn't seem to be done correctly, resulting in odd and missing keys.
- Missing turfs were re-added.
This was done by just copying the new changes onto a known good copy, so there's a decent chance I missed something, sorry. Still better than hundreds of runtimes a second.

Fix prison map runtimes/missing turfs/smoothing

---

tools/bootstrap/python37._pth
tools/bootstrap/python_.ps1
tools/mapmerge2/convert.py
tools/mapmerge2/dmm.py
tools/mapmerge2/fixup.py

The python version in dependencies.sh was updated to 3.7.9, but Bootstrap was still expecting python 3.6. This broke the map and DMI merge hooks, mapmerge, and several of the map tests when running locally.
These are important tools!

Fix mapmerge and merge hooks

---

code/modules/power/apc.dm

Ports a fix for APCs having infinite power if one tick tries to consume a number of kilojoules higher than the cell's number of watt-ticks, because of a missing conversion factor.

Port fix for infinite APC power from Citadel

---

code/controllers/subsystem/research.dm
code/datums/components/nanites.dm
code/game/machinery/computer/Operating.dm
code/game/machinery/computer/dna_console.dm
code/game/machinery/doppler_array.dm
code/modules/atmospherics/gasmixtures/reactions.dm
code/modules/mob/living/carbon/life.dm
code/modules/power/singularity/collector.dm
code/modules/power/tesla/coil.dm
code/modules/research/experimentor.dm
code/modules/research/machinery/_production.dm
code/modules/research/nanites/nanite_program_hub.dm
code/modules/research/nanites/nanite_programs.dm
code/modules/research/nanites/nanite_programs/utility.dm
code/modules/research/nanites/program_disks.dm
code/modules/research/rdconsole.dm
code/modules/research/server.dm
code/modules/research/techweb/_techweb.dm
code/modules/surgery/experimental_dissection.dm
code/modules/surgery/tools.dm

Fixes #300.
Overhauls research to remove hardcoded techwebs and fix the inconsistency with networks generating points. This should allow mappers to add/handle new networks easily.
TODO IN A FUTURE PR: Move all the duplicated `research_id`, `linked_techweb`, and `update_techweb` vars/procs to a `/datum/technology_connection` or promote it to /obj/machinery.
Will hopefully make it easier to add new tech networks for factions, as well as remove ones that aren't used, and link machinery.

[NEEDS TESTING] Overhaul SSResearch for custom techwebs/networks

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

The Legion fortress was missing seeds this whole time! Oops. Gives them two wheat seeds, two xander seeds, and two broc seeds.

Add missing seeds to Legion fortress

---

code/game/machinery/autolathe.dm
code/modules/farming/farming_structures.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
code/modules/jobs/job_types/wasteland.dm

- Fixes settlers getting 50 single sheets of wood and metal, rather than two stacks of 50 sheets.
- Allow seeds to be extracted in bulk via plant bags.
- Allow plants to be fermented in bulk via plant bags.
- Allow fridges and racks to be loaded automatically from *all* storage, not just bags.
I've been getting terrible wrist pain and developing repetitive stress injuries from all the repeated spam clicking and wrist movements involved in making bitters and poultices while playing Legion slave. Most stuff that requires spamclicking like that should be removed in favor of bulk actions, to save people's wrists.
:cl:
add: Added bulk fruit fermentation. By clicking a fermenting barrel with a plant bag, all the suitable plants in it will be fermented.
add: Added bulk seed extraction. By …

Removes carpal tunnel syndrome from the game

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
_maps/map_files/Pahrump-Sunset/Warren-Upper.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
code/modules/fallout/areas/area.dm

Fixes badly mapped APCs in the BoS and derelict bunker, and tidies up some other ones as well.
Adds separate Wasteland area subtypes for each map section to cut down on some of the weird weather behavior. TODO: Do the same with building, city, raider, etc.

Mapping fixes, August 17 2022

---

code/modules/mapping/space_management/multiz_helpers.dm

This isn't really a big deal, just a minor annoyance that might result in weather not reaching the higher levels of a z-stack. It's not mission critical or anything, but it's a good fix to have regardless.

Fix for surface blocks generating before mapload

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
code/game/objects/effects/landmarks.dm
code/game/objects/items/cards_ids.dm
code/modules/jobs/job_types/bos.dm
code/modules/jobs/job_types/enclave.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm

- - -
Map:
- Rock Springs upper given interiors.
- Venator quarters added.
- Brotherhood given a communications terminal.
- - -
Balance:
- Science focused jobs, Enclave Scientist and Scribes specifically, given poor aim.
- Sniping focused roles, Veteran Ranger, Venator and Explorer, given insane aim.
- Various head roles given terrifying presence.
- Enables the Baron role.
- - -
Fixes:
- Venator given proper spawn and ID.
- Explorer given proper spawn and ID.
- Slavemaster no longer starts nude for a majority of species, aside from Human. Comments out the unique undersuit to accomplish this.
- - -

Balance Adjustments

---

code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm

Disables Behemoth gibbing, bringing it in line with expectations. Both rule wise and otherwise.

Be-gib be-gone

---

code/modules/projectiles/guns/ballistic/automatic.dm

-Minorly increased the assault carbine's damage output
-Minorly increased the assault carbine's rate of fire
-Substantially increased the assault carbine's armor penetration capabilities
-Police Rifle adjusted accordingly
Applied to a degree to the worn assault carbine.
Gives it a place in the weapon sandbox as a fast-firing rare firearm with high AP.
COMPARED TO OTHER HIGH TIER LOOT/FACTION WEAPONS
As it stands ^
-The R93 PDW can now take a bayonet attachment
-The R93 PDW has a fire delay of 1.15 from 3.25
-The R93 PDW has a slowdown of 0.15 instead of 0.5

significant assault carbine buff + R93 touch up

---

code/__DEFINES/mobs.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm

- - -
Consumables now provide 3 value to water level, up from 0.1, as this value wasn't adjusted in error to mirror other buffs. This might make things like hot dogs give you water level but whatever. I'll fix it eventually.
- - -
Thirst rate dropped from 0.2 to 0.1, significantly reducing difficulty. Again.
- - -
Grenade casings can be made again.
- - -

Thirst Adjustments & Grenade Casings

---

code/modules/smithing/finished_items.dm

I tested all of them in actual gameplay, it's why this PR took so long to go up. It's fucking insane. There's no reason it should ever be this high, like at all.
I solo-raided the NCR with a Wakizashi and got to walk in and walk out nigh unscathed.
And 1v7'd them twice, and came out victorious. It's not good, anyone and everyone has full access to it. It's barely about skill. I mean-
Look at this shit, man
Gives katana and wakizashi wound bonuses, especially for the unarmored
Katana has its own individual block parry data variable now
Li'l saber nudge

Severely handicaps blocking in smithed weapons

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

- - -
Simple change to catwalks in lower Pahrump, setting them to be plated beneath. Because, for some reason, they don't stop you from walking ON tiles that they cover. This led to players being irradiated without reason.
- - -

Plating Under Catwalks

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm

Lowers the required damage threshold check for Sentrybots down to 30, from 40.

Sentrybot Rebalance

---

code/modules/projectiles/guns/ballistic/automatic.dm

As they stand, sniper rifles have zero place in the weapon sandbox because they're outclassed in every way by the Colt Rangemaster, which is fairly common and present in a plethora of spots, on top of being part of a Ranger loadout, and able to be crafted roundstart by the Logistics Officer.
This turns the sniper rifle into a high-risk high-reward weapon, locking you into 8 round magazines but giving you the ability to dispatch targets quickly as long as you can follow up shots. In a way, it now performs similarly to how the Rangemaster used to but slightly better.
The Rangemaster change still keeps it as a high-damage semi-automatic all-purpose gun.
**COLT RANGEMASTER**
- DMG 35 < 40
- ARMOR PENETRATION 18% < 20%
**SNIPER RIFLE**
- DELAY 3 < 4
- BULLET SPEED 900 < 800
- SLOWDOWN 0.3 < …

Rebalances Rangemaster and Sniper and draws a difference

---

code/__DEFINES/misc.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm
code/modules/mob/living/carbon/human/species_types/synthanthro.dm
code/modules/mob/living/carbon/human/species_types/synthliz.dm
code/modules/mob/living/carbon/human/species_types/synths.dm
code/modules/projectiles/guns/ballistic/rifle.dm
code/modules/projectiles/projectile/bullets/rifle.dm

- - -
Balance:
- AMR is now semi-automatic for those that have the fast-pump trait, which is given automatically to the Veteran Ranger.
- AMR damage up from fifty(50) to sixty(60).
- AMR penetration bonus up from 0.6 to 1.
- Legion Explorer has lost Insane Aim, making it exclusive to the singular Venator and Veteran Ranger roles.
- HMG round damage up from five(5) to fifteen(15).
- Standard heavy munitions (.50 / 12.7) given a wound bonus of twenty(20), and a bare wound bonus of sixty(60)
- - -

Buffs Large Calibre Munitions - .50 / 12.7

---

code/modules/jobs/job_types/enclave.dm

(I don't know Github's policy on naughty words, so the title is censored, to make sure I don't get ****ed)
Gives the Enclave Lieutenant, Gunnery Sergeant and Sergeant the Researcher trait, letting them use the R&D console.
The Enclave, at deadpop, can honestly just be (and often is) one or two people with neither playing Scientist. This makes it so they're not just sitting around with pretty much nothing of substance to do. Besides, as longtimers in the Enclave, Sergeants+ would have picked up a thing or two from all the Scientists around.

Enclave Research Unf***ing

---

code/game/mecha/mecha_defense.dm

Basically makes it so you can put mechs in maintanance mode and then wrench them to make them draggable, allowing you to pull them up and down ladders. This still means you have to get out of the mech and be vulnerable while doing it, but makes it so you dont have to walk mechs all the way over to bighorn just to use them topside, otherwise mechs have seen zero usage. 
Credit to Lyro#2540 for helping with the code, as I'm just a spriter.

Freedom for Mechs

---

_maps/pahrump.json
code/controllers/subsystem/mapping.dm
code/game/atoms.dm
code/game/machinery/doors/windowdoor.dm
code/game/turfs/open.dm
code/game/turfs/openspace/openspace.dm
code/game/turfs/turf.dm
code/modules/atmospherics/environmental/LINDA_system.dm
code/modules/atmospherics/gasmixtures/gas_mixture.dm
code/modules/fallout/turf/floor.dm
code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
code/modules/hydroponics/grown/towercap.dm
code/modules/mapping/space_management/multiz_helpers.dm
code/modules/mapping/space_management/traits.dm
code/modules/mapping/space_management/zlevel_manager.dm
code/modules/mob/living/say.dm
code/modules/power/gravitygenerator.dm

- Fixes runtime from bonfires burning items.
- Fixes runtime from items being thrown into windoors.
- Fixes runtime from saying "." or ":".
- Fixes runtime from dismantling f13 wood floors.
- Fixes a runtime that meant longpork stew didn't consume its ingredients properly.
- Makes z-level logic (gravity, above/below) much faster.
- Shaves like 10-20 seconds off init with air system optimisations.
- Adds a wrapper proc to help debug our atmos lag.

Fixes and upgrades, September 3 2022

---

code/modules/jobs/job_types/bos.dm

Gives The med-x recipe to scribes, honestly wouldn't be super surprised if this is just power creep and gets rejected, but thought it made sense for them to have it considering they get the chemistry trait, decided to not give them the wasteland chems though, as it would make little sense for scribes to be making stuff like psycho.

Med-X for scribes

---

code/modules/projectiles/guns/ballistic/automatic.dm

SHOT DELAY 2 < 4
AUTOMATIC FIRE 1.1 < 2.2
ARMOR PENETRATION 35% < 10%
Grants the weapon an actual fire support role and makes it compete with other faction leader weapons (There is no reason to pick it over CQC or the AMR as it stands)

Makes the M1919 better across the board

---

code/game/objects/items/storage/belt.dm

Just some small changes to make the Medoiler an item that's perhaps actually used. Allows it to carry pill bottles, bottles, syringes, stimpacks and medical sprays, rather than only specifically syringe gun syringes. Still should be plenty balanced over the medical belt as it cant carry anything bulky like surgery tools or medical bags. 
Should be a good pick for field medics who want to reliably carry consumables into the field.

Medolier Changes

---

code/modules/fallout/obj/structures/mob_spawners.dm

Oops. Didn't realise spawners weren't originally infinite by default.

Fix nests defaulting to infinite

---

code/modules/jobs/job_types/followers.dm
code/modules/projectiles/guns/energy/plasmaf13.dm

Gives the admin the same traits as the doctors; they lacked researcher. Also gave them the advanced cyberneticist trait because they didn't have the basic one, and the admin is supposed to be the most experienced of the bunch there.

Gives follower admin same traits as doctor

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
code/modules/jobs/job_types/enclave.dm

Changes:
- Swaps the sidearms for the Enclave Lieutenant's loadouts. Previously, there was no reason to take the ballistics loadout, as the plasma loadout was just straight up better. Now the first loadout gets a ballistic rifle and plasma sidearm, and second loadout gets a plasma rifle and ballistic sidearm.
- Gives the Enclave Gunnery Sergeant Command access. Useful for the next change.
- Adds command access to the Gunnery Sergeant's box, puts the trait books and money inside. Prevents random Privates from taking the Gunny's stuff.
- Places the collars, keys and signaller that were previously in the Gunny's box on the shelf next to it, for easy access.
- Removes one of the shelves in the Gunny's office, as it was just wasting space.
- Moves the borders of the "Enclave Bunker" area to …

Enclave Changes and Fixes (Highly subjective)

---

code/modules/vehicles/rubbish.dm

Buffs the chance of getting advanced pre-war salvage from cars from a whopping 3 percent to 6 percent. On high pop, getting salvage becomes extremely painful when a handful of people will run to all the meta machinery places and take it all for themselves. Last round as of this PR, I scrapped every single car in yuma, taking about an a hour, only to get nine pieces of advanced salvage. Which also means I left none for everyone else and barely had enough for myself.
Yes this is a salt PR.

Car Welding Advanced-Pre War Salvage Buff

---

code/modules/projectiles/projectile/beams.dm

In Fallout: New Vegas, the AER14 had a green beam.
For some reason, on the server it does not have a green beam, but a blue beam, while the AER12 has a green beam instead. This changes that.
Gives the AER12 a blue beam, and give the AER14 a green beam.
Locally tested, it works, as expected.
Credit to Nepotism for the suggestion and me for the code changes.

Swap AER12 and AER14 beam colours

---

code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

- - -
Balance:
- Glowing Ghouls can no longer revive other Glowing Ghouls. Instead, they detonate into a cloud of radiation and gib. This prevents them stacking, but doesn't stop utility of the burst.
- Since Aggro is broken, they no longer radburst when detecting you.
- Radburst cooldown significantly increased.
- - -

Glowing Ghoul Adjustment

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/vehicles/_vehicle.dm
code/modules/vehicles/wasteland/motorcycle.dm
code/modules/vehicles/wasteland/vehicle_fuel.dm

- - -
This PR was initially intended to add keycard energy fields to the game, as might be hinted by the branch name. I've discarded that for now, however, and hadn't bothered to change the branch name.
- - -
Balance:
- Initial introduction of Motorcycles as a faction based object. The NCR gets a Ranger bike, with the key in the Veteran's quarters. The Legion must brave the Renegade camp to get their bike. Otherwise, a rusted bike, with ten percent slowdown, is present in the fire station. That's three bikes in total, one per map. This is likely to be adjusted, as the values for the bikes aren't tweaked and you can snake with them.
- HMG Mutant given rebalances, post viewing of how it functions in game.
- Rock Springs firewatch tower given a proper perimeter wall, to make utilizing it as …

Motorcycles & Madness

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/__DEFINES/jobs.dm
code/game/machinery/doors/unpowered.dm
code/game/objects/effects/landmarks.dm
code/game/objects/items/cards_ids.dm
code/game/objects/items/granters.dm
code/game/objects/items/storage/boxes.dm
code/modules/clothing/suits/f13factionarmor.dm
code/modules/clothing/suits/light_armor.dm
code/modules/clothing/suits/medium_armor.dm
code/modules/clothing/under/f13.dm
code/modules/jobs/job_types/bighorn.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/khan.dm
code/modules/jobs/job_types/khan_OLD.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/jobs.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/shuttle/f13.dm
modular_citadel/code/modules/client/loadout/head.dm
modular_citadel/code/modules/client/loadout/suit.dm
modular_citadel/code/modules/client/loadout/uniform.dm

- - -
The primary purpose of this PR is to devalue the roles of the Khans, that being inflated, and returning the Town to being an RP hub. This doesn't remove the Khans, just returns them to chem pushers. From the nonsense names to the replacement of Townie roles, it was a nightmare that this PR correct.
Their stated goal is to gather caps, for a nondescript 'Chief', assuredly the one that was previously in Bighorn. No more hugging it out in the temple of Pax.
- - - 
Balance:
- Auxilia given one ambrosia deus.
- Followers (DOCTORS) provided poor aim, to discourage combat-medic behaviour. Or actively seeking conflict. You know why this was done.
- Bighorns' set of gates now begin closed. View additions for _why_.
- Bank Vault door replaced by a standard command door, accessible by the …

Khan-B-Gone

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
_maps/map_files/Pahrump-Sunset/Warren-Upper.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
code/__DEFINES/is_helpers.dm
code/game/objects/structures/table_frames.dm

- - -
Balance:
- Various mid-to-high tier gun spawns sprinkled around the Valley.
- Singular Deathclaw Spear spawns in the valley, within the coom shack. Go find it.
- Securitrons, mostly, replaced by Protectrons.
- NML loot table buffed significantly with high end ballistics.
- Brotherhood's topside area blocked off by default, the tunnel needing to be cleared and given a reason not to be meta'd.
- Legion's reloading bench removed, replaced with the improved version that has basic recipes unlocked, alongside a twenty stack of gunpowder.
- NCR's fully unlocked reloading bench (what the fuck why) has been removed, given an identical bench to the Legion. This was pretty blatant favoritism.
- All major factions can once again access NML.
- Legion capable of accessing the rear of the crusher …

Tables & NML

---

code/game/objects/items/stacks/sheets/sheet_types.dm

Reduces the time to make barricades to 5 seconds down from 13 and adds craftable wooden shelves and cabinets from the wooden use menu, under furniture.

Barricades, Closets and Shelves

---

code/modules/projectiles/guns/ballistic/automatic.dm

- The Colt Monitor now behaves like a very slow, cumbersome FAL. It's nowhere near as devastating for active quick combat due to this, and essentially forces you into:
1. - Using cover
2. - Having allies

Colt Monitor balance pass

---

code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

Massively tanks the radiation damage of the Reaver's radioactive projectile. This lowers it to 25, from 250.

Reaver Adjustment

---

code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

- - -
Balance:
- Halves Feral and Reaver health.
- Glowing Ghoul check for range on rad bursting is raised to six, from three.
- - -

Ghoul Touchup

---

code/modules/mob/living/silicon/robot/robot_modules.dm
modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm

Alternative to #488 
Reduces base cyborg health to 150
Reduces medical assaultron health to 300 from 450
Replaces the K9's integrated AER9 with an integrated AEP7
Saying that "all cyborgs have been buffed" isn't genuine, considering every _selectable_ cyborg prior to #485 already had 300 health or more (Gutsies = 300, Assaultrons = 450)
Still, I've lowered non-combat oriented borgs health by 150. This leaves the janitorial and medical dogborgs at 150 health, the security dogborg and gutsies at 300, and the assaultron at 450.
The medical assaultron had no downsides compared to the regular one, which is why now they have less health (300). They still get to have double the health of the other non-combat borgs.
As an oversight the security K9 borgs were given AER9s. Now they have the same …

Cyborg balance changes

---

code/modules/projectiles/boxes_magazines/internal/shotgun.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/projectile/bullets/shotgun.dm

**T**he purpose of this PR is to bring needed relevancy to low-capacity shotguns and to make buckshot a relevant threat in the face of other ammo types (Right now it's just a mob deterrent lol)
- DAMAGE 40 < 50
- WOUND BONUS 35 < 26
- BARE WOUND BONUS 10 < -26
- ARMOR PENETRATION 25% < 0
- DAMAGE 11.3 < 11
- WOUND BONUS 35 < 0
- BARE WOUND BONUS 75 < 0
- EXTRA DAMAGE 5.2 < 0
- EXTRA PENETRATION 10% < 0
- EXTRA DAMAGE 3.5 < 0
- EXTRA PENETRATION 5% < 0
- FIRING DELAY 4 < 5
- FIREMODE FULL < SEMI
- MAX AMMO 10 < 12
- RECOIL 1.25 < 0

BUFFS SHOTGUN AMMO & DOUBLE BARRELS + NO AUTOSHOTGUN SIDEGRADES

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Removes the DNA manipulator from the rocksprings bottom left 'dungeon'. The only faction that ever gets this is the legion, because no one is going to try and contest legion. The legion should not be using a dna manipulator and the only good reason is powergaming, no one else in the wasteland can grab one of these boards, so either it should be removed, or other factions should have access to them. 
Or at the very least it should be put in a more center dungeon that's more difficult.

DNA manipulator board removal.

---

code/modules/projectiles/guns/ballistic/automatic.dm

Reduces the movespeed penalty of (thus far) the combat rifle and the rangemaster.
Rangemaster movespeed penalty reduced to 0.3 from 0.4
Combat rifle movespeed penalty reduced to 0.25 from 0.5 (Absurd)
This brings the two guns down to a better baseline with the rest of the semi-automatic weapons in the game. The best example is the marksman carbine with 0.2 movespeed and comparable stats to the changed weapons.
Combat rifle movespeed was reduced to 0.25 as 0.5 was simply absurd for a semi-auto weapon with its stats and fire delay. Seriously.
Rangemaster movespeed was reduced to 0.3 from 0.4 because it only has 1 more damage and 0.8 more AP than the marksman carbine, along with increased projectile speed. It's fire delay is however double that of the marksman carbine. Simply put, whilst it …

Reduces the movespeed penalties of a few semi-automatic weapons.

---

code/game/machinery/deployable.dm
code/game/objects/items/stacks/rods.dm
code/game/objects/items/stacks/sheets/mineral.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/objects/items/stacks/stack.dm

Simply adds a check when crafting a few structures (like sandbags, tables or barbed wire) to check they don't have another defensive structure under them.
(Also deletes some strange blank spaces left in the deployables file for some reason)
The defense meta has become so deeply-ingrained that every round the factions are basically _forced_ to spend an hour or more building the perfect unbreachable position.
This PR looks to break it up a little, especially the table + sandbags meta that was, in all honesty, an exploit, as you couldn't climb over them. This time that is no longer spent building can be spent roleplaying.
This also does away with some of the cheesing in dungeons.

Prevents stacking of defensive structures

---

code/modules/clothing/head/_head.dm
code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/head/f13head.dm
code/modules/clothing/suits/_suits.dm
code/modules/clothing/suits/armor.dm
code/modules/clothing/suits/f13armor.dm
code/modules/clothing/suits/f13factionarmor.dm
code/modules/clothing/suits/f13suits.dm
code/modules/clothing/suits/heavy_armor.dm
code/modules/clothing/suits/light_armor.dm
code/modules/clothing/suits/medium_armor.dm
modular_citadel/code/modules/reagents/objects/clothes.dm
modular_sunset/code/modules/clothing/suits/f13suits.dm

Gave light armor (anything with below 0.1 slowdown) 10 wound armor, medium armor (anything between 0.1-0.2) 20 wound armor, heavy around (anything above 0.2) 30 wound armor and PA 50 wound armor.
This was based on feedback and seeing the issue with shotguns.

Wound Armor Balancing

---

code/modules/jobs/job_types/enclave.dm

Raises enclave scientist roles from 2 to 3. Why? We have 5 labs. Only 2 scientists. Enclave should not be raiding to begin with and scientists got the "No you cant go out and raid" flag on them. I'd argue for 4 slots but lets see if 3 is sufficient.  
Allows for 3 scientists to exist, allows to actually get things done and allows to work better on projects without putting all the pressure on two scientist players that have to manage the entire base full of soldiers wanting some good support and probably having to do a surgery or two if they get killed in the field.  Atleast it should raise the slots by 1. Not sure if spawn points need to be raised. Its changing one number. Man I am good at coding. 
I get somebody that actually has patience to check if this would boot up. Should though, …

Adds another Enclave scientist

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/_globalvars/lists/maintenance_loot.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/granters.dm
code/modules/WVM/wvm.dm
code/modules/fallout/areas/area.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
code/modules/jobs/job_types/bos.dm
modular_sunset/code/mob/renegade.dm

- - -
Balance:
- PA Wear can no longer be obtained from lootdrop. You require training roundstart, or staff intervention to obtain it. Get to RPing. This locks the suits to Enclave and Brotherhood.
- Chemistry, Technophile and Surgery and all variations removed from the general Wastelander trait book, alongside Tribal. The books have also been removed from circulation loot wise, to create some manner of actual RP around the Followers and give them a purpose.
- Knights no longer have PA Wear, with the exception of the Knight-Commander.
- Initiate has lost basic surgery.
- Brotherhood no longer have a power requirement. For now.
- - -
Map:
- Brotherhood vault emptied. Provided two fluff items in the center. Kind of.
- - -

Trait Rebalance

---

code/modules/jobs/job_types/ncr.dm

**NCR Scout Sergeant / NCR Patrol Ranger**
- Removed the free 50-round magazines.
**NCR Heavy Trooper**
- Added Flamethrower loadout (M2 Flamethrower, heavy service rifle)
- NCR HT now spawns with the Big Leagues trait, letting them deal an extra 10 damage with any melee weapon.

ASSHOLE NCR BIAS CODER DRAGONFRUITS BUFFS HIS FAVORITE FACTION AGAIN (FALLOUT 13 IS !RUINED!)

---

code/game/objects/items/storage/belt.dm
code/modules/clothing/custom/custom_clothing.dm
modular_citadel/code/modules/client/loadout/__donator.dm

- - -
Added my own loadout. Funny abuse time woohoo. Armor has next to no protection outside of utility, and is used for a ghoul character as is, so that's another thing to tack on. It's thematically centred around being hazard equipment and is practically useless in PvP except for the fire immunity, which isn't really used outside of the NCR as is.
Helmet trades practically all protection for utility, and retains flash resist and the NVG overlay, which is worthless for ghouls anyway and not that great as is.
General armor layout, for the suit and helmet, with the rest having identical without actual protection values aside from utility (The 100 row.):
- melee/bullet/laser = 5
- energy = 65
- bomb = 5
- bio/rad/fire/acid = 100
- wound = 15
The exception is the uniform, which has no …

Hee-Hoo Carl Loadout Abuse

---

code/modules/jobs/job_types/legion.dm

Adds a gladius to the Recruit Decanus' backpack. For some reason they didn't have one beforehand. Now they do.

Recruit Decanus Gladius

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
_maps/shuttles/cargo_pahrump.dmm
code/game/objects/items/circuitboards/machine_circuitboards.dm
code/game/objects/items/devices/radio/headset.dm
code/modules/fallout/areas/area.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/station_goals/dna_vault.dm
fortune13.dme
modular_sunset/code/modules/defenses/mortar.dm

- - -
Balance:
- Brotherhood provided the Cargo elevator from the Vault.
- Brotherhood given the DNA Vault.
- Brotherhood bunker given a minor rework to permit easier defence during raids.
- Brotherhood once again require power, of which they'll get from a reactor.
- Brotherhood given the second portable mortar in their armory. We'll see how this works out.
- - -
Corrections:
- Enclave headsets can now be de-linked.
- Paladin Dense is now a separate mob, rather than a rename, to prevent the FEB randomized name.
- Portable mortar no longer called the M204, erroneously, and is now renamed to M29, as per its parent.
- Recyclers no longer turn each other on. For better or worse.
- - -

Brotherhood Rebalance | Other Changes

---

code/game/objects/effects/spawners/f13lootdrop.dm

Adds the correct ammo for the combat rifle
:cl:
fix: Replaces grease gun mags with tommygun sticks on the lootspawn with the combat rifle.
/:cl:

Combat rifle spawner bugfix

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Changes the Followers protolathe back into the regular, after Carl made an oopsie and changed it back to a medical lathe accidentally.

Follower Protolathe

---

code/modules/clothing/suits/f13armor.dm

Currently T-51b (both regular and midwestern) have 30 energy armor.
Hardened T-51b (both regular and midwestern) has 27 energy armor, this is most likely an oversight. 
It's basically just an increment of a few points to match in line with the slight improvements of hardened T-51b in most categories comparative to regular T-51b. Literally an oversight fix.
:cl:
tweak: Fixes an oversight where hardened T-51b had less energy armor than regular T-51b.
/:cl:

Fixes regular T-51b having more energy resistance than hardened T-51b

---

code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm

It uncomments and re-adds the radio headset to the workshop T-comms list.
It allows wastelanders and outlaws to be able to walk around with a radio that doesn't require you to manually turn it on from your backpack since we don't have :l or :r in this code. This was a change made in Coyote Bayou that was merged in Sunset Wasteland back in July 26 and no one ever bothered to change. This will make things better since it'll be a Quality of Life, since every faction already gets a headset anyway.
:cl:
tweak: uncomments the radio headset
/:cl:

uncomments the radio headset

---

code/modules/clothing/masks/miscellaneous.dm
code/modules/clothing/suits/f13factionarmor.dm
code/modules/jobs/job_types/bighorn.dm
code/modules/projectiles/boxes_magazines/ammo_boxes.dm

Fixed both variations of the desert facewrap to hide the player's snout when equipped on face so the snout doesn't poke out of the facewrap. Issue observed ingame.
Swaps Captain's reinforced armor and LT's armor stats. Gave the LT's armor 30 melee defense rather then 25. Issue reported on discord.
Fixed Farmer loadout on the citizen role not getting their pistol. Issue #395
Fixed .22lr ammo boxes from going invisible. Issue #465
Bugs bad. Ugly snout peeking through facewrap bad. 
:cl:
/:cl:

Small bugfix

---

code/game/objects/items/melee/f13onehanded.dm
code/modules/clothing/masks/miscellaneous.dm
modular_citadel/code/modules/client/loadout/__donator.dm

- - -
Provides an unremovable mask for Baghead. Not much else to be said, aside from pointing out its flags.
* resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF
* clothing_flags = BLOCK_GAS_SMOKE_EFFECT|ALLOWINTERNALS|THICKMATERIAL|SCAN_REAGENTS
- - -

Baghead's Loadout

---

code/game/objects/structures/timeddoor.dm
code/modules/cargo/packs/emergency.dm
code/modules/cargo/packs/service.dm
code/modules/clothing/head/f13head.dm
code/modules/clothing/head/f13heavy_helmets.dm
code/modules/clothing/suits/f13armor.dm
code/modules/clothing/suits/heavy_armor.dm
code/modules/jobs/job_types/bos.dm
code/modules/jobs/job_types/enclave.dm
code/modules/jobs/job_types/wasteland.dm

- - -
Enclave:
- Returns PA values to about where they were prior. I'll be reworking PA entirely, but I'm afraid it'll have to sit here for now. It's only two suits at the moment, with the following change.
- A specialised tesla suit given to the Gunnery Sergeant, slightly weaker in ballistic and melee protection, but near immune to energy and lasers.
- Bunker Duty jumped from two slots to six, to mirror BoS off-duty.
- - -
Wasteland:
- Outlaw/Raider dropped from infinite slots to six. We don't get folks using it for anything other than Wastelander+, so we'll be nipping that in the bud. We'll likely go back to infinite soon.
- - -
Other:
- It is no longer possible to buy ATV/Snowmobile packages.
- Removal of Hardened PA from Brotherhood Marshal. This was unintended.
- - -

Enclave Touchup & Other

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/Warren.dmm
code/modules/projectiles/projectile/bullets/dart_syringe.dm
code/modules/projectiles/projectile/bullets/pistol.dm

- - -
Bighorn:
- Shopkeep's store positioned in a far better way, given much more loot and overall made into an actual warehouse with absurd stuff. As we don't permit raiding on the store normally, this shouldn't be an issue.
- Lower bar lost its drink machines, to give more attention to the upper location. It's likely that I'll just gut this area altogether soon.
- Schoolhouse for Followers replaced near entirety of the three offices.
- - -
Enclave:
- Enclave bunker given a minor touchup. Only Command roles can access the Armory by default now. This is an identical access requirement to the reactor.
- Armory updated to provide three needlers, two combat rifles and an ion rifle.
- Additional landing locations added within the Mountain Range. One outside and one far north-east.
- - - …

Various Map Corrections | Pass #1

---

code/game/objects/effects/spawners/f13lootdrop.dm

This comments out the AMR, Gauss Rifle and Bozar blueprints from loot tables, making them no longer up to chance to spawn.
This should help balancing, stopping mass-production of incredibly unique weapons, and giving them more importance rather than them being a common sight.
:cl:
balance: removed the AMR, Gauss Rifle and Bozar blueprints from the loot tables
/:cl:

comments out the AMR, Gauss and Bozar blueprints

---

modular_citadel/code/modules/client/loadout/__donator.dm

Custom loadout, mostly for convenience; it's quite literally the outcast loadout with a recharger pistol instead of the AEP7, blueprint, and frags (oof), but I've gotten this so many times in game that I'd prefer to just have it since it makes sense the character would keep it.

Custom loadout

---

code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/projectile/bullets/rifle.dm

Lowered overall damage of 5.56 and lowered armored wound bonus, at the cost of increasing the round's default speed.
Also buffs 5.56 pistol to stay relevant with these changes.
Added supereffective damage against animals to "Hunting" rounds, and gave generalized supereffective damage against simplemobs to high caliber/powerful ammo like .50 BMG and 2mm

5.56 rebalance + supereffective ammo

---

code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/suits/f13factionarmor.dm
code/modules/jobs/job_types/ncr.dm

Practically all of the NCR's armor has been revised in some way. Most of the time, to make it weaker so that it can match the rest of the gear in the game (It also gives NCR a reason to use converted CA/RCA like other factions often do)
VETERAN RANGER ARMOR IS NO LONGER STUPIDLY BROKEN.
Trekking is no longer a free trait that's tossed around to every member of the NCR willy-nilly. You need to specify in scouting/frontlining in the more important roles if you want roundstart trekking.
Veteran Ranger must now specialize in "rifling" for the autopump trait. Brush gun replaced with a medicine stick.
Brotherhood combat armor is generally more resilient to lasers and energy than regular combat armor.
Also updated slowdown appropriately for their RCA, used to be faster for some reason.
Fixed …

UNFROKIFY NCR + MISC

---

_maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/game/objects/items/melee/f13onehanded.dm
code/game/objects/items/storage/survivalkit.dm

- - -
Balance:
- Stamina damage on batons upped to sixty, from thirty. This is probably a horrible idea, but we'll try it.
- Large survival kits temporarily removed.
- Enclave access to chameleon masks and IDs returned.
- Enclave IS loses telescopic shields.
- - -
Map:
- Enclave given personal lockers again.
- - -

Miscellaneous Changes

---

code/modules/projectiles/projectile/beams.dm

Makes the plasma beam used by repeaters powerful again. The mining version did 5 damage, and the repeater did 10 less, the mining beam has been restored to it's previous damage, and the normal version has been buffed to it's damage as well, the idea is to use them for an automatic plasma weapon (plasma caster?)

Making plasma great again

---

code/modules/admin/DB_ban/functions.dm
code/modules/admin/IsBanned.dm
code/modules/admin/create_poll.dm
code/modules/admin/ipintel.dm
code/modules/library/lib_machines.dm
code/modules/mob/dead/new_player/poll.dm
code/modules/shuttle/emergency.dm

Technically it's less sanitizing and more using the [Rust mysql crate's named parameters](https://docs.rs/mysql/latest/mysql/#named-parameters) and rust-g's SQL handling to make prepared statements not a pain in the ass, but this also happens to prevent SQL injection, which is "sanitized" enough for me even though we're not really doing any input processing or anything.
Quotes in ban edit reasons won't cause the entire statement to explode.
(I can't be assed to set up a local database and run through all of these functions just for testing this, honestly.)

Sanitize most string interpolations in queries

---

code/modules/clothing/suits/f13factionarmor.dm
code/modules/clothing/suits/heavy_armor.dm

Despite its stat weakness, NCR Armor now has the highest amount of wound protection out of every faction. 
I also further tweaked some values that I deemed too weak.
I've significantly reduced the slowdown you get from wearing it, so it can have a spot in the sandbox and not be a useless bloat item that you don't pick out of sheer uselessness.
Down from 100 slowdown, SPA now starts from 60 slowdown to 35 slowdown depending on armor quality and rarity, with the latter being for the rarest, most exotic sets.
I changed the slowdown of the heavy steel vest to 20 up from 10. It's ridiculous otherwise.

FURTHER NCR ARMOR CHANGES + BUFF SALVAGED POWER ARMOR

---

code/modules/projectiles/projectile/bullets/shotgun.dm

**Shotgun slugs**
Slugs now do 90 damage to supermutants, deathclaws, raiders, robots, and radscorpions due to being armor piercing.
**Incendiary slugs**
Incendiary slugs now do 100 damage to ants, cazadors, and radscorpions.
**Buckshot**
Buckshot now does 21 DAM/pellet to an assortment of mobs.

Shotgun PVE buff

---

code/modules/clothing/suits/f13factionarmor.dm

Apparently initiate armor is a child of regular brotherhood CA. And it has no independent stats.
This changes it.

Fix initiate armor

---

code/game/objects/items/melee/f13onehanded.dm
code/game/objects/items/melee/f13twohanded.dm
code/modules/smithing/finished_items.dm
modular_citadel/code/modules/client/loadout/__donator.dm

**A load of melee weapons can parry now, most of them two handed.
Parrying is more punishing but also doesn't reward a good connection, windows are longer.**
Parries now only apply a single hit when succeeding.
Generic parries have a 10% (per decisecond) effectiveness falloff past their perfect window.
Also removed the cringy katana thing unique item that just exists for some reason.

Properly tweaks parrying

---

code/game/objects/effects/spawners/f13lootdrop.dm

Adds salvaged PA to the Tier 5 Armor (Power Armor) spawn, and weights it towards it.
Unguaranteed PA spawns means you no longer know for sure if you're gonna find PA at a certain spot.
:cl:
balance: unguarantees PA spawns
/:cl:

Ungaurantees PA lootdrops

---

code/modules/cargo/packs/emergency.dm
code/modules/cargo/packs/engineering.dm
code/modules/cargo/packs/goodies.dm
code/modules/cargo/packs/medical.dm
code/modules/cargo/packs/security.dm

HRP ROUND CONTINUITY + COMPLETELY AXE TRAIT BOOK CRATE FROM BOS.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/pahrump.json
code/modules/cargo/packs/engineering.dm
code/modules/projectiles/projectile/special/rocket.dm

- - -
Balance:
- Chemical rocket shrapnel magnitude dropped from six to two.
- - -
Map:
- Wrench and multitool now present within the Bighorn reactor area round start.
- Map name clarified from Yuma to its actual name.
- - -
Other:
- Minor description changes to two cargo packs.
- - -

Minor Modifications

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/__DEFINES/jobs.dm
code/game/objects/items/melee/f13onehanded.dm
code/modules/jobs/access.dm
code/modules/jobs/job_types/khan.dm
code/modules/jobs/jobs.dm
code/modules/projectiles/boxes_magazines/internal/shotgun.dm
code/modules/projectiles/guns/ballistic/automatic.dm

- - -
Balance:
- Throwing spears are now more-or-less guaranteed to embed, and are less likely to fall out on walking. The chance was upped from 60% to 95% for embedding, and the fall chance was lowered from 20% to 5%.
- Neostead now starts with trainshot as its primary load.
- MF legendary ghoul swapped with a proper glowing one, within the upper area.
- - -
Factions | Khan Related:
- Khans now get a unique scrap sabre.
- Khan loadouts redone slightly, providing them a competitive ranged option.
- Khan leadership roles updated. They now have a Senior Enforcer.
- Senior Enforcer gets, guaranteed, three-thousand caps roundstart.
- Chemist slots raised by one.
- - -
Map:
- MF is now roundstart accessible by the Khans, but the timers remain for all other entrances.
- Khan camp updated.
- - - …

Khan QoL & Other Changes

---

code/datums/traits/good.dm

Reworked formal tribal quirk to actually be tribal light. it was a hold over from dessert rose that completely gutted you and made you able to use LESS tech than a standard tribal. basically removed the tech negative and made you able to use a alchemy bench. bumped cost up by one point to reflect this. you do not get the special crafting recipes a tribal gets tho. as ya became more use to modern life you forgot your tribal craft ways.
:cl:
stuff
/:cl:

Formal tribal quirk rework

---

modular_citadel/code/modules/client/loadout/__donator.dm

This pull request creates a custom loadout option for Alffd that makes a character half-synth on round-start.
This has two different setups, a basic one that would apply to any role and only adds a massive EMP weakness, and an Enclave Scientist one with a larger set of more balance impacting implants that are restricted round-start to a RP-only flagged role.  This should save about 30-45 minutes a round on implants that are used for RP purposes.
:cl:
add: Alffd custom half-synth loadout
/:cl:

Alffd Fluff

---

code/datums/components/nanites.dm
code/modules/research/nanites/nanite_programs/utility.dm

This PR adds a new variable to nanite datums called "spreading" and modifies health/nanite scanners to not detect nanites marked with the "stealth" variable unless the "spreading" variable is also set.
Spreading is controlled by the spreading nanite program, stealth by the stealth program.
The only faction in the game with nanite technology is the Enclave, as an always valid faction they tend to go out in disguises without any obvious equipment.  This has been countered by the Brotherhood printing nanite scanners to scan people they don't recognize for nanites so they can valid them.
Two solutions were presented, the first which I have not coded would be to have a nanite scan take 5 or more seconds and allow the person being scanned to break it by moving.  This makes it more painful to …

Stealth nanites, now with stealth

---

code/modules/mob/living/carbon/human/examine.dm

This PR removes the ability of medical huds to scan for implants.
This does not effect any other type of scanning, handheld scanners not not effected by this PR, nor does this PR implement any other methods of dealing with implants.
This _only_ covers the medical hud.
Currently undercover scribes and Enclave can be detected via implants by anyone looking at them with a medical hud.  
While this has occurred in the past, it has now happened recently enough that it makes sense to break this PR out from a monolithic solution.
:cl:
balance: You can nolonger see a persons implants just by looking at them with a hud, you must use a health scanner.
/:cl:

Remove hud scanning of implants

---

README.md

Fixes some incorrect notes/instructions in the README.md, fixes links that went to incorrect or nonexistent places.
Someone complained that the wiki link went to the broken Fandom wiki. Also, info on Auxmos and setup should be included and accurate.

Fix links and notes in readme

---

code/__DEFINES/maps.dm
code/datums/components/area_sound_manager.dm
code/datums/elements/weather_listener.dm
code/datums/looping_sounds/_looping_sound.dm
code/datums/weather/weather_types/ash_storm.dm
code/modules/admin/verbs/possess.dm
code/modules/mob/login.dm

Taken mostly from https://github.com/tgstation/tgstation/pull/71282. Undoes most of the changes I made to area sound managers, should be much faster and more performant now. Also makes the base ashstorm type have a probability of 0, but also makes it able to be adminspawned in the Wasteland.
It's annoying.

Fix ash storm sounds looping forever

---

dependencies.sh
tools/ci/install_auxmos.sh
tools/tgs4_scripts/PreCompile.sh

- Separates the addition of `AUXMOS_REPOSITORY` to `dependencies.sh` from #721 out into a separate PR.
- Also separates the editing of the precompile script into this PR.
This is so that the game doesn't break if we untestmerge the Auxmos 2.1.1 PR; it can just re-grab the proper version from the repo.

Make auxmos downloading more robust, add auto-build to precompile script

---

modular_citadel/code/modules/client/loadout/hands.dm

Not tested. Should add a spraycan to the item loadout hands category.
Allows people to paint the loadout items they start with regardless of job or proximity to the nearest public clothesmate (Bighorn)
Or just allows you to have graffiti on hand. QoL eitherway because you can just craft these from a workshop.
:cl:
add: spraycan to loadout
/:cl:

Adds spraycan to loadout options

---

modular_citadel/code/modules/client/loadout/__donator.dm

This adds a pair of Enclave Private dogtags for Davusi as a special loadout, they have no access associated with them.
Devusi, a wastelander.  Jumped aboard a departing Vertibird and managed to convince both POs that he was a Enclave Private returning from the wastes, upon arriving he managed to convince the faction to provide him with access to the armory and an Agent ID with full access to the bunker.  This continued for a good amount of time until discovery, tricking two pilot officers, two sergeants, one enlisted, and an IA officer.
This is to commemorate them tricking high-pop Casper into thinking they were one of them by jumping on a helicopter and shouting about how great the Enclave was.
:cl:
add: Davusi dogtags
/:cl:

Davusi dogtag fluff

---

modular_citadel/code/modules/client/loadout/__donator.dm

This is no longer needed as I am pretty much done with the place and set my mind on other things. Please remove the kit. 
Wat kümmerts den Mond wenn 'ne Töle ihm anheult. Als ob mich dat wat kümmert obs funzt. Geht alle voll fett ma einen abseilen. Lappen. Ohne Scheiß und asideutschen Sarkasmus, sollte klappen, entfernt nur was Unnötiges. Fick die Gammastrahlenpistole.
It should work. 
:cl:
del: The nanite swarm now builds a tower at the southpole or something. In other words removes donor kit as it is no longer needed as the player is no longer active.
/:cl:

Removes a custom kit

---

code/modules/smithing/anvil.dm
code/modules/smithing/finished_items.dm

**Katana**
fold fold fold fold fold > fold fold fold fold fold fold fold fold fold fold
Parrying bonus damage changed from 1x on average to 1.5x on average
**Smithed Dagger**
STANDARD FORCE 24 > 19
**Wakizashi**
STANDARD FORCE 25 > 21
WOUND CHANCE  15 > 25
**Smithed Mace**
STANDARD FORCE 15 > 17
EXTRA STAMINA DAMAGE 15 > 20
**Smithed Katana**
WIELDED DAM. MULTIPLIER 1.5x > 1.4x
WOUND CHANCE 25 > 35
**Smithed Axe**
Can no longer parry.
**Smithed Javelin**
ARMOR PENETRATION 10% > 15%
EMBED CHANCE 60 > 75
**Smithed Throwing Knife**
STANDARD FORCE 14 > 13
ARMOR PENETRATION 0% > 5%

Tweak parrying and smithed weapons again

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/shotgun.dm

-Spread raised significantly.
SPREAD 10 > 16
DAMAGE REDUCTION 0 > 6
ARMOR PENETRATION 0 > 15%
EXTRA DAMAGE 0 > 10
EXTRA PENETRATION 0 > 12%
DAMAGE REDUCTION 0 > 3
SPECIAL: FULLY AUTOMATIC
DAMAGE REDUCTION 5 > 3
ARMOR PENETRATION 20% > 17%
FIRERATE 2.95 > 2.45
DAMAGE REDUCTION 5 > 3
ARMOR PENETRATION 0 > 5%
FIRERATE 1.75 > 1.85
ARMOR PENETRATION 45% > 40%
DAMAGE REDUCTION 5 > 7
ARMOR PENETRATION 0 > 10%
DAMAGE REDUCTION 0 > 5
ARMOR PENETRATION 0 > 15%
SLOWDOWN 50% > 12%
ARMOR PENETRATION 0 > 5%

Tweak a batch of guns

---

code/game/objects/items/stacks/stack.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Ckeys for loadout items should be lowercase. This fixes that.
Yanniert asked nicely for me to fix it.
Did you know that when debugging via Dream Daemon, you can use `#guest_override ckey` and join as a guest to join with that ckey? That means you can, in fact, test loadout PRs locally.

Fix Canis' Teachings ckey

---

code/datums/traits/_quirk.dm
code/game/atoms.dm
code/game/turfs/f13concrete.dm
code/modules/clothing/head/_head.dm
code/modules/fallout/turf/ground.dm
code/modules/hydroponics/grown/cotton.dm
code/modules/hydroponics/grown/towercap.dm
code/modules/hydroponics/hydroponics.dm
code/modules/mob/living/brain/brain_item.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

Fixes several runtimes. Tested:
Bugfixes!

Runtime fixes, December 15 2022

---

code/datums/wounds/_scars.dm
code/datums/wounds/_wounds.dm

Fixes wounds not clearing refs properly.
This is probably the cause of the random CI fails on master.
Random CI fails are bad, things GCing is good.

Fix wounds failing to GC

---

code/modules/jobs/job_types/legion.dm

removes lifegiver from veteran legionary and recruit decanus

Legion salt nerf

---

code/game/mecha/mech_fabricator.dm
code/game/objects/items/robot/robot_upgrades.dm
code/modules/projectiles/guns/energy/kinetic_accelerator.dm
code/modules/research/designs/mechfabricator_designs.dm

CHANGE LOG
CHANGE 1, Fixed self-repair, so that it is no longer stuck in a loop
CHANGE 2 Added traits to the surgical processor so that medical robots are granted sci-related traits when
CHANGE 3, Changed the readable name on the surgical processor to something fallout-related, Changed flavor text very slightly
Change 4, added flags to robot modules in robot_upgrades.dm So that they appear in the correct list in the exo fab
CHANGE 5, added else if(U in typesof(/obj/item/borg/upgrade/modkit))
sub_category += "Mining" to mech_fabricator.DM so that mining_designs.dm is placed properly in the exofab screen.
TLDR; Self-repair works, Surgical processor renamed, and adds traits to Medical borgs when installed, allowing them to do chem, research, and surgery. Correctly organized the exofab …

Lurze cyborg bug fix pass 1

---

code/modules/reagents/chemistry/holder.dm

Fixes doing `istype(thing.type, type)` instead of `istype(thing, type)`.
Fixes hydrotrays again. My bad.

Fix water not being consumed by hydrotrays

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/jobs/job_types/enclave.dm
code/modules/projectiles/guns/ballistic/launchers.dm
code/modules/projectiles/guns/energy/laser.dm

- - -
Balance:
- Returns the L30 to the Platoon Sergeant.
- Grenade Launcher made identical in size to the rocket launcher.
- Removes ability to get PA Wear, as intended.
- - -
Other:
- Name of the standard gatling laser changed to a lore inaccurate, but hopefully understandable name. It follows US experimental naming conventions. Kind of.
- - -

Minor Balance Tweaks

---

code/controllers/subsystem/idlenpcpool.dm

Lowers the worst-case mob wakeup time from 12 seconds to 2 seconds, making it 6x faster.
People complained about being able to skip past mobs that should've absolutely seen you. Rather than have a rule against it, it'd be better to just make them wake faster.

Reduce worst-case mob wakeup time to 2 seconds (6x faster)

---

code/modules/integrated_electronics/core/assemblies.dm
code/modules/integrated_electronics/core/integrated_circuit.dm

Fixes circuits harddeling, which takes up a disproportionate amount of SSGarbage CPU time.
SSGarbage is once again at the top of the profiler, mostly due to circuits.

Fix circuits harddeling

---

modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm

- - -
Simply prevents players from mixing and getting three different chems that aren't appropriate in the current environment.
- - -

Reaction Disabling
